import assert from 'node:assert/strict';
import test from 'node:test';
import { buildBenchmark, buildMarketConditions, buildRateIntelligence, calculateDeadhead, findBackhaulOpportunities, negotiationRecommendation, planMultiLegTrip, rankLoadsForTruck, rankTrucksForLoad, scoreTruckForLoad } from '../src/services/freightIntelligence.js';

const load = { id:'l1', originCity:'Regina', destinationCity:'Calgary', equipmentType:'Dry van', weightKg:10000, distanceKm:760, pickupDate:'2026-08-14T18:00:00Z', budgetCents:240000 };
const truck = { id:'t1', equipmentType:'Dry van', capacityKg:20000, currentCity:'Regina', availableAt:'2026-08-14T12:00:00Z', maximumDeadheadKm:100, desiredDestination:'Calgary', homeTerminal:'Calgary' };

test('load to truck matching is ranked and explainable', () => { const rows=rankTrucksForLoad(load,[truck,{...truck,id:'t2',equipmentType:'Reefer'}],{t1:{deadheadKm:18,carrierRating:4.8,lanePerformance:.9,costs:{costPerKm:1.2}}}); assert.equal(rows[0].truckId,'t1'); assert.ok(rows[0].score>=80); assert.ok(rows[0].reasons.includes('Correct equipment')); assert.equal(rows.some(row=>row.truckId==='t2'),false); });
test('truck to load ranking returns best compatible load', () => { const rows=rankLoadsForTruck(truck,[load,{...load,id:'l2',equipmentType:'Flatbed'}],{l1:{deadheadKm:12}}); assert.equal(rows[0].loadId,'l1'); });
test('deadhead separates deadhead, loaded and trip cost', () => { const row=calculateDeadhead({deadheadKm:100,loadedKm:900,costPerKm:1.5}); assert.equal(row.deadheadPercent,10); assert.equal(row.deadheadCostCents,15000); assert.equal(row.estimatedTripCostCents,150000); });
test('backhaul ranks true return load first', () => { const rows=findBackhaulOpportunities(load,[{id:'b1',originCity:'Calgary',destinationCity:'Regina',equipmentType:'Dry van'},{id:'b2',originCity:'Edmonton',destinationCity:'Regina'}]); assert.equal(rows[0].load.id,'b1'); assert.equal(rows[0].score,100); });
test('multi-leg plan reports HOS estimate and economics', () => { const row=planMultiLegTrip([load,{id:'l2',originCity:'Calgary',destinationCity:'Regina',distanceKm:760,budgetCents:220000}],{costPerKm:1.1,maxDrivingHours:13}); assert.equal(row.returnToTerminal,true); assert.ok(row.warnings.some(w=>w.includes('HOS'))); assert.equal(row.hosLabel,'OPERATIONAL_ESTIMATE_NOT_HOS_CERTIFIED'); });
test('rate engine returns insufficient data with sample context', () => { const row=buildRateIntelligence([{amountCents:200000,kind:'POSTED'}],{distanceKm:700}); assert.equal(row.status,'INSUFFICIENT_DATA'); assert.equal(row.observations,1); assert.equal(row.suggestedRateCents,null); });
test('rate engine uses accepted Loadlyx observations and exposes confidence', () => { const observations=[210000,220000,230000,240000].map((amountCents,index)=>({amountCents,kind:'ACCEPTED',source:'LOADLYX_NETWORK_DATA',occurredAt:new Date(Date.now()-index*86400000)})); const row=buildRateIntelligence(observations,{distanceKm:800}); assert.equal(row.status,'AVAILABLE'); assert.equal(row.observations,4); assert.ok(row.confidence>0); assert.equal(row.dataLabel,'LOADLYX_NETWORK_DATA'); });
test('negotiation assistant requires human approval', () => { const rates=buildRateIntelligence([210000,220000,230000].map(amountCents=>({amountCents,kind:'ACCEPTED'})),{distanceKm:700}); const row=negotiationRecommendation({askingCents:240000,rateIntelligence:rates,economics:{estimatedTripCostCents:160000,deadheadPercent:4}}); assert.equal(row.requiresHumanApproval,true); assert.ok(row.openingOfferCents<240000); });
test('market condition label is derived from first-party counts', () => { const row=buildMarketConditions({loads:[{},{}],trucks:[{}],accepted:[]}); assert.equal(row.band,'TIGHT'); assert.equal(row.dataLabel,'LOADLYX_NETWORK_DATA'); });
test('benchmark protects small cohorts and anonymizes eligible cohorts', () => { assert.equal(buildBenchmark({subject:{},cohort:[{},{}]}).status,'SUPPRESSED_FOR_PRIVACY'); const cohort=Array.from({length:5},(_,i)=>({revenuePerMile:2+i/10,deadheadPercent:10+i,offerAcceptanceRate:50+i,averageMargin:20+i,onTimePickup:90,onTimeDelivery:88,cancellationRate:2,averageSettlementHours:48,averageLoadValue:2000+i*20})); const row=buildBenchmark({subject:cohort[0],cohort}); assert.equal(row.status,'AVAILABLE'); assert.equal(row.anonymized,true); });
test('matching confidence identifies missing data instead of fabricating it', () => { const row=scoreTruckForLoad(load,truck); assert.ok(row.missingInputs.includes('deadhead distance')); assert.ok(row.confidence<92); });
