'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { adminFetch } from '../../../lib/adminFetch';
import { ErrorState, LoadingState, PageHeader, StatusBadge } from '../../../components/ui/LoadlyxUI';

export default function PaymentSettingsPage() {
  const [data, setData] = useState(null);
  const [form, setForm] = useState({ paypalMerchantId: '', payoutMethod: '', payoutDestinationLabel: '' });
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  async function load() { const response = await adminFetch('/payment-settings'); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Unable to load payment settings'); setData(body); if (body.scope === 'TENANT') setForm({ paypalMerchantId: body.settings.paypalMerchantId || '', payoutMethod: body.settings.payoutMethod || '', payoutDestinationLabel: body.settings.payoutDestinationLabel || '' }); }
  useEffect(() => { load().catch((err) => setError(err.message)); }, []);
  async function save(event) { event.preventDefault(); setError(''); setMessage(''); const response = await adminFetch('/payment-settings', { method: 'PUT', body: JSON.stringify(form) }); const body = await response.json(); if (!response.ok) return setError(body.error || 'Unable to save settings'); setData((current) => ({ ...current, settings: body.settings })); setMessage('Payment and payout settings saved.'); }
  async function connectStripe() { setError(''); const response = await adminFetch('/payment-settings/stripe/onboarding', { method: 'POST', body: '{}' }); const body = await response.json(); if (!response.ok) return setError(body.error || 'Unable to start Stripe onboarding'); window.location.assign(body.url); }
  return <main className="container"><PageHeader eyebrow={data?.scope === 'PLATFORM' ? 'Platform integrations' : 'Tenant finance'} title="Payments and payouts" description={data?.scope === 'PLATFORM' ? 'Global provider readiness. Tenant-owned payout accounts are configured inside each tenant workspace.' : 'Connect the accounts that receive tenant store and marketplace proceeds. Loadlyx never asks tenants to paste secret API keys here.'} actions={data?.scope === 'TENANT' ? <Link className="btn secondary" href="/admin/balance">Open ledger & withdrawals</Link> : null} />{error ? <ErrorState message={error} /> : !data ? <LoadingState label="Loading payment settings" /> : data.scope === 'PLATFORM' ? <div className="grid grid-3">{Object.entries(data.providers || {}).map(([name, provider]) => <section className="card" key={name}><h2>{name.toUpperCase()}</h2><StatusBadge tone={provider.status === 'CONFIGURED' ? 'success' : provider.status === 'DISABLED' ? 'warning' : 'neutral'}>{provider.status}</StatusBadge><pre className="muted small" style={{ whiteSpace: 'pre-wrap' }}>{JSON.stringify(provider, null, 2)}</pre></section>)}</div> : <div className="grid two" style={{ gap: 20 }}><section className="card"><h2>Stripe Connect</h2><p className="muted">Secure onboarding handles identity, bank details, charges and payouts on Stripe.</p><p><StatusBadge tone={data.settings.stripeConnected ? 'success' : 'warning'}>{data.settings.stripeConnected ? 'Connected' : data.stripeAvailable ? 'Ready to connect' : 'Platform Stripe not configured'}</StatusBadge></p><button className="btn" disabled={!data.stripeAvailable} onClick={connectStripe}>{data.settings.stripeConnected ? 'Update Stripe account' : 'Connect Stripe'}</button></section><section className="card"><h2>PayPal and withdrawal destination</h2><p className="muted">Provider mode: {data.paypalMode}</p><form className="grid" style={{ gap: 12 }} onSubmit={save}><label>PayPal merchant ID<input value={form.paypalMerchantId} onChange={(e) => setForm({ ...form, paypalMerchantId: e.target.value })} placeholder="Merchant ID (never a secret key)" /></label><label>Preferred payout method<select value={form.payoutMethod} onChange={(e) => setForm({ ...form, payoutMethod: e.target.value })}><option value="">Choose a method</option><option value="STRIPE">Stripe</option><option value="PAYPAL">PayPal</option><option value="MANUAL">Manual bank payout</option></select></label><label>Destination label<input value={form.payoutDestinationLabel} onChange={(e) => setForm({ ...form, payoutDestinationLabel: e.target.value })} placeholder="Example: Business account ending 1234" /></label><button className="btn" type="submit">Save payout settings</button>{message ? <p className="success" role="status">{message}</p> : null}</form></section></div>}</main>;
}
