'use client';
import { useEffect, useState } from 'react';
import { adminFetch } from '@/lib/adminFetch';
import { EmptyState, PageHeader, StatusBadge } from '@/components/ui/LoadlyxUI';

export default function SecurityControlsPage(){
 const [blocks,setBlocks]=useState([]);const [message,setMessage]=useState('');const [form,setForm]=useState({targetType:'IP',targetValue:'',reason:'',expiresAt:'',warningAccepted:false});
 async function load(){const response=await adminFetch('/operations-map/security/blocks');const body=await response.json();if(!response.ok)throw new Error(body.error||'Unable to load security controls');setBlocks(body);}
 useEffect(()=>{load().catch(error=>setMessage(error.message));},[]);
 async function create(event){event.preventDefault();if(!window.confirm('Apply this backend-enforced security block? Shared IPs can affect unrelated people.'))return;const response=await adminFetch('/operations-map/security/blocks',{method:'POST',body:JSON.stringify({...form,expiresAt:form.expiresAt||undefined})});const body=await response.json();if(!response.ok)return setMessage(body.error||'Unable to create block');setMessage('Security block applied and audited.');setForm({targetType:'IP',targetValue:'',reason:'',expiresAt:'',warningAccepted:false});load();}
 async function revoke(id){const reason=window.prompt('Reason for removing this block:');if(!reason)return;await adminFetch(`/operations-map/security/blocks/${id}`,{method:'DELETE',body:JSON.stringify({reason})});load();}
 return <main className="container grid" style={{gap:24}}><PageHeader eyebrow="Super Admin · Security" title="IP, user, session, and device controls" description="Backend-enforced, temporary or permanent controls with reasons and immutable audit events. Avoid broad network blocks and protect emergency Super Admin recovery."/>{message?<p className="notice">{message}</p>:null}<form className="card grid" onSubmit={create}><h2>Create a security block</h2><div className="grid grid-3"><label>Target type<select value={form.targetType} onChange={e=>setForm({...form,targetType:e.target.value})}>{['IP','USER','SESSION','DEVICE'].map(value=><option key={value}>{value}</option>)}</select></label><label>Target value<input required value={form.targetValue} onChange={e=>setForm({...form,targetValue:e.target.value})} placeholder="IP, user ID, or session identifier"/></label><label>Expires (optional)<input type="datetime-local" value={form.expiresAt} onChange={e=>setForm({...form,expiresAt:e.target.value})}/></label></div><label>Reason<textarea required minLength="8" value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label>{form.targetType==='IP'?<label className="checkbox-row"><input type="checkbox" checked={form.warningAccepted} onChange={e=>setForm({...form,warningAccepted:e.target.checked})}/> I understand this IP may be shared by a VPN, mobile carrier, household, or business network.</label>:null}<button className="btn" type="submit">Review and apply block</button></form><section className="card"><h2>Active blocks</h2>{blocks.length?<div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Type</th><th>Target</th><th>Reason</th><th>Expires</th><th>Action</th></tr></thead><tbody>{blocks.map(block=><tr key={block.id}><td><StatusBadge tone="warning">{block.targetType}</StatusBadge></td><td>{block.targetDisplay||'Protected value'}</td><td>{block.reason}</td><td>{block.expiresAt?new Date(block.expiresAt).toLocaleString():'Permanent'}</td><td><button className="btn ghost" onClick={()=>revoke(block.id)}>Remove</button></td></tr>)}</tbody></table></div>:<EmptyState title="No active security blocks" description="Login activity remains available on the operations map."/>}</section></main>;
}
