import Link from 'next/link';

export const marketingPages = {
  'solutions/moving-companies': ['Moving company software', 'Run leads, estimates, quotes, dispatch, crews, customer updates, payments, and supplies from one accountable workspace.', ['Capture every lead', 'Quote faster with structured inventory', 'Coordinate crews and dispatch', 'Sell supplies in your own storefront']],
  'solutions/brokers': ['Freight brokerage, connected', 'Post customer freight, compare qualified carrier offers, preserve agreed terms, and coordinate delivery without exposing private commercial details.', ['Privacy-safe public previews', 'Versioned offers and negotiations', 'Broker margin controls', 'Delivery and settlement evidence']],
  'solutions/carriers': ['Better freight opportunities for carriers', 'Find eligible loads, submit clear offers, manage execution, and build a trustworthy operating record.', ['Relevant load discovery', 'Structured offers', 'Pickup and delivery tracking', 'Controlled payout readiness']],
  'solutions/shippers': ['A clearer way to move freight', 'Create a shipment request, compare providers, follow progress, and keep documents and communication connected.', ['Guided load posting', 'Protected contact details', 'Provider comparison', 'Trackable delivery workflow']],
  'platform/crm-quotes': ['CRM and quotes that move work forward', 'Keep leads, customers, inventories, estimates, and follow-up in one operational record.', ['Structured intake', 'Reusable quote workflows', 'Approval-ready AI drafts', 'Conversion visibility']],
  'platform/dispatch': ['Dispatch without the spreadsheet scramble', 'Coordinate jobs, crews, carriers, dates, exceptions, and customer updates from a shared operating view.', ['Assignment clarity', 'Conflict visibility', 'Status tracking', 'Role-aware access']],
  'platform/store-commerce': ['Branded commerce for moving businesses', 'Publish products, bundles, rentals, and services in a tenant-isolated storefront connected to inventory and fulfilment.', ['Tenant branding', 'Catalog and categories', 'Secure checkout readiness', 'Order fulfilment']],
  'platform/ai-automation': ['AI assistance with human authority', 'Prepare summaries, follow-ups, matches, and recommendations under tenant limits and approval controls.', ['Explainable recommendations', 'Approval gates', 'Usage controls', 'Auditable outcomes']],
  'platform/payments': ['Payments designed for accountable operations', 'Connect checkout, commissions, refunds, payouts, and immutable ledger records without hiding provider readiness.', ['Server-authoritative totals', 'Provider status transparency', 'Commission policies', 'Refund and payout controls']],
  'platform/analytics': ['Analytics grounded in real operations', 'Understand demand, conversion, revenue, fulfilment, and marketplace activity while keeping demo data explicitly isolated.', ['Operational KPIs', 'Revenue paths', 'Tenant boundaries', 'Demo-safe reporting']],
  'resources/getting-started': ['Getting started with Loadlyx', 'Choose the account path that matches your role, complete verification, and open the correct workspace.', ['Create your account', 'Verify your email', 'Complete role onboarding', 'Start your first workflow']],
  'resources/loadboard-guide': ['Loadboard guide', 'Learn how public previews, protected details, posting, offers, and marketplace roles work together.', ['Browse safely', 'Sign in for protected details', 'Post a complete load', 'Review eligible offers']],
  'resources/store-guide': ['Storefront launch guide', 'Prepare branding, categories, products, policies, checkout settings, and fulfilment before inviting customers.', ['Brand the tenant', 'Build the catalog', 'Review payment readiness', 'Test fulfilment']],
  'resources/security': ['Security and trust', 'Loadlyx uses verified accounts, server-side authorization, tenant scoping, audit records, and explicit provider status.', ['Verified-email controls', 'Least-privilege roles', 'Tenant isolation', 'Auditable financial actions']],
  'legal/terms': ['Terms of Service', 'These terms govern access to and use of the Loadlyx platform and its tenant workspaces.', ['Use the service lawfully', 'Keep account credentials secure', 'Respect tenant and marketplace boundaries', 'Provider services may have separate terms']],
  'legal/privacy': ['Privacy Policy', 'This policy explains the information Loadlyx processes to operate accounts, tenant services, commerce, and the marketplace.', ['Account and transaction data', 'Operational and security records', 'Provider-directed processing', 'Access and correction requests']],
  'legal/marketplace-terms': ['Marketplace Terms', 'These terms apply when posting, offering on, accepting, or completing marketplace loads.', ['Accurate load information', 'Authorized offers and acceptance', 'Private details stay protected', 'Payment and dispute rules apply']],
  'legal/acceptable-use': ['Acceptable Use Policy', 'Use Loadlyx safely and do not misuse accounts, data, communications, payments, or marketplace access.', ['No fraud or impersonation', 'No abusive automation', 'No unauthorized data access', 'No unlawful goods or activity']],
  'legal/cookies': ['Cookie Policy', 'Loadlyx uses essential storage for authentication, security, preferences, and reliable operation.', ['Essential session storage', 'Security and fraud prevention', 'Preference storage', 'Analytics only when configured']],
  'legal/payments': ['Payment and Transaction Terms', 'Payment providers process supported transactions while Loadlyx records authorized totals, commissions, and status changes.', ['Provider availability varies', 'Totals are server-authoritative', 'Refund rules follow the transaction', 'Payouts require eligibility checks']]
};

export default function MarketingDetailPage({ pageKey }) {
  const [title, description, points] = marketingPages[pageKey] || [];
  if (!title) return null;
  const legal = pageKey.startsWith('legal/');
  return <main className="lx-marketing-page"><section className="lx-marketing-hero"><div className="lx-page-header"><span className="lx-eyebrow">{legal ? 'Loadlyx legal' : 'Loadlyx'}</span><h1>{title}</h1><p>{description}</p><div className="lx-hero-actions"><Link className="btn" href={legal ? '/signup' : '/signup'}>{legal ? 'Create an account' : 'Start Free'}</Link><Link className="btn secondary" href={legal ? '/' : '/pricing'}>{legal ? 'Back to Loadlyx' : 'View Pricing'}</Link></div></div></section><section className="lx-section"><div className="lx-feature-grid">{points.map((point, index)=><article key={point}><span>{String(index + 1).padStart(2, '0')}</span><h2>{point}</h2><p>{legal ? 'This requirement supports a safe, transparent relationship between Loadlyx, tenants, providers, and users.' : 'Built into the connected Loadlyx workflow with clear permissions and operational visibility.'}</p></article>)}</div>{legal ? <p className="muted" style={{marginTop:32}}>Effective August 18, 2026. Contact support through your Loadlyx account for questions about these terms.</p> : null}</section></main>;
}
