'use client';
import { useEffect, useState } from 'react';
import { adminFetch } from '../../../lib/adminFetch';
import { DataTable, ErrorState, LoadingState, PageHeader, StatCard, StatusBadge } from '../../../components/ui/LoadlyxUI';
const money = (value) => `$${((value || 0) / 100).toFixed(2)}`;

export default function BalanceAdminPage() {
  const [balance, setBalance] = useState(null); const [withdrawals, setWithdrawals] = useState([]); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [requesting, setRequesting] = useState(false);
  async function loadBalance() { const [balanceResponse, withdrawalsResponse] = await Promise.all([adminFetch('/balance'), adminFetch('/withdrawals')]); const data = await balanceResponse.json(); const withdrawalRows = await withdrawalsResponse.json(); if (!balanceResponse.ok) throw new Error(data.error || 'Unable to load balance'); if (!withdrawalsResponse.ok) throw new Error(withdrawalRows.error || 'Unable to load withdrawals'); setBalance(data); setWithdrawals(withdrawalRows); }
  useEffect(() => { loadBalance().catch((err) => setError(err.message)); }, []);
  async function requestWithdrawal() { if (!balance?.availableCents || requesting) return; if (!window.confirm(`Request withdrawal of ${money(balance.availableCents)}?`)) return; setRequesting(true); setMessage(''); setError(''); const idempotencyKey = crypto.randomUUID(); try { const response = await adminFetch('/withdrawals/request', { method: 'POST', headers: { 'Idempotency-Key': idempotencyKey }, body: JSON.stringify({ amountCents: balance.availableCents, currency: 'cad', idempotencyKey }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Withdrawal request failed'); setMessage('Withdrawal request created and added to the audit history.'); await loadBalance(); } catch (err) { setError(err.message); } finally { setRequesting(false); } }
  const columns = [{ key: 'entry', label: 'Ledger entry', render: (row) => <div><strong>{row.entryType}</strong><div className="muted small">{row.transaction.kind}</div></div> }, { key: 'status', label: 'Status', render: (row) => <StatusBadge tone={row.transaction.status === 'SETTLED' ? 'success' : 'warning'}>{row.transaction.status}</StatusBadge> }, { key: 'direction', label: 'Direction', render: (row) => row.direction }, { key: 'amount', label: 'Amount', render: (row) => <strong>{row.direction === 'DEBIT' ? '−' : '+'}{money(row.amountCents)}</strong> }];
  const withdrawalColumns = [{ key: 'createdAt', label: 'Requested', render: (row) => new Date(row.createdAt).toLocaleString() }, { key: 'method', label: 'Destination', render: (row) => <span>{row.payoutMethod}<small>{row.destinationRef || 'Configured destination'}</small></span> }, { key: 'status', label: 'Status', render: (row) => <StatusBadge tone={row.status === 'COMPLETED' ? 'success' : row.status === 'FAILED' ? 'danger' : 'warning'}>{row.status}</StatusBadge> }, { key: 'amount', label: 'Amount', render: (row) => <strong>{money(row.amountCents)}</strong> }];
  return <main className="container"><PageHeader eyebrow="Tenant settlement" title="Balance and payouts" description="See available, earned, reserved, and withdrawn funds backed by immutable ledger and request records." actions={<button className="btn" disabled={!balance?.availableCents || requesting} onClick={requestWithdrawal}>{requesting ? 'Requesting…' : 'Request available balance'}</button>} />{error ? <ErrorState message={error} /> : !balance ? <LoadingState label="Loading tenant balance" /> : <><section className="lx-stat-grid"><StatCard label="Available" value={money(balance.availableCents)} detail="Eligible for withdrawal" tone="green"/><StatCard label="Earned" value={money(balance.earnedCents)} detail="Lifetime credited proceeds"/><StatCard label="Reserved" value={money(balance.reservedCents)} detail="Held for settlement" tone="orange"/><StatCard label="Ledger entries" value={balance.ledger?.length || 0} detail="Auditable financial events" tone="purple"/></section>{message ? <p className="lx-form-message" role="status">{message}</p> : null}<section className="lx-panel" id="withdrawals" style={{ marginTop: 20 }}><div className="lx-panel-header"><div><h2>Withdrawal requests</h2><p>Every request is idempotent and remains visible through review, processing, completion, or failure.</p></div></div><DataTable columns={withdrawalColumns} rows={withdrawals} emptyTitle="No withdrawal requests" emptyDescription="Connect a payout destination, then request eligible funds."/></section><section className="lx-panel" id="ledger" style={{ marginTop: 20 }}><div className="lx-panel-header"><div><h2>Immutable ledger</h2><p>Credits, debits, and their transaction state.</p></div></div><DataTable columns={columns} rows={balance.ledger || []} emptyTitle="No ledger entries" emptyDescription="Financial activity will appear when transactions settle."/></section></>}</main>;
}
