import Link from 'next/link';
import { Icon, SectionHeading, StatusBadge } from '../../components/ui/LoadlyxUI';

const workflows = [
  ['Moving companies','users','Lead capture, AI-assisted estimates, quotes, dispatch, crews, customer communication, payment, and follow-up in one operating path.'],
  ['Brokers','chart','Post customer loads, compare qualified offers, negotiate terms, preserve the agreement, collect payment, and coordinate providers.'],
  ['Carriers','route','Find eligible loads, submit structured offers, manage pickup and delivery evidence, build trust, and receive controlled payouts.'],
  ['General customers','store','Post a personal load, compare providers, fund the accepted agreement, track delivery, leave verified reviews, and buy moving supplies.'],
  ['Store operators','store','Publish products and variants, manage inventory and images, fulfill orders, operate branded themes, and reconcile tenant proceeds.'],
  ['Platform operations','spark','Govern users, tenants, fees, subscriptions, simulation, risk, reviews, AI, integrations, and immutable financial records.']
];

export default function SolutionsPage() {
  return <main className="lx-marketing"><section className="lx-section lx-hero"><div className="lx-hero-copy"><span className="lx-eyebrow"><i />Loadlyx Connect</span><h1>A connected freight network for every participant.</h1><p>Loadlyx Connect brings freight, carriers, drivers, brokers, tracking, offers, and execution into one connected logistics network while preserving role and tenant boundaries.</p><div className="lx-hero-actions"><Link className="btn lx-btn-lg" href="/signup">Choose your account path</Link><Link className="btn secondary lx-btn-lg" href="/pricing">Compare plans</Link></div></div><div className="lx-product-mockup"><div className="lx-mockup-bar"><strong>Role-aware workspace</strong><StatusBadge tone="success">Connected</StatusBadge></div><div className="card"><h2>Demand â†’ agreement â†’ operations â†’ settlement</h2><div className="stack-sm">{['Capture the right customer and load details','Compare transparent, versioned offers','Fund only the accepted agreement','Release proceeds after delivery controls'].map((item) => <div className="summary-line" key={item}><Icon name="check" /><strong>{item}</strong></div>)}</div></div></div></section><section className="lx-section"><SectionHeading eyebrow="Role-specific solutions" title="The right tools, permissions, and next steps for every actor." description="Each workflow shares a trusted platform foundation while preserving tenant isolation, marketplace privacy, and backend authorization."/><div className="lx-feature-grid">{workflows.map(([title,icon,body]) => <article key={title}><span><Icon name={icon}/></span><h3>{title}</h3><p>{body}</p></article>)}</div></section><section className="lx-section lx-why-section"><div><span className="lx-eyebrow">AI with approval controls</span><h2>Recommendations assist the work. People retain authority.</h2><p>AI can prepare descriptions, summaries, follow-ups, matches, risk signals, and commerce opportunities under tenant limits and approval policies. It does not silently award loads, change pricing, or release money.</p></div><div className="card"><h3>Built for accountable operations</h3>{['Tenant-scoped data','Explainable recommendations','Usage and cost tracking','High-impact approval gates','Audit history'].map((item) => <p key={item}><Icon name="check" size={16}/> {item}</p>)}</div></section><section className="lx-section lx-final-cta"><div><span className="lx-eyebrow">Start with your workflow</span><h2>Turn disconnected demand into booked, profitable work.</h2><p>Create a marketplace account or launch a tenant workspace with the plan that matches your operation.</p></div><div><Link className="btn lx-btn-lg" href="/signup">Start free</Link><Link className="btn secondary lx-btn-lg" href="/loadboard">Explore the load board</Link></div></section></main>;
}

