'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { adminFetch } from '../../../lib/adminFetch';
import { DataTable, ErrorState, LoadingState, PageHeader, StatusBadge } from '../../../components/ui/LoadlyxUI';
const money = (value, currency = 'CAD') => new Intl.NumberFormat('en-CA', { style: 'currency', currency: currency.toUpperCase() }).format((value || 0) / 100);

export default function MarketplaceTransactionsPage() {
  const [rows, setRows] = useState(null); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  async function load() { const response = await adminFetch('/marketplace/transactions/mine'); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Unable to load marketplace transactions'); setRows(data); }
  useEffect(() => { load().catch((err) => setError(err.message)); }, []);
  async function pay(row) { try { const response = await adminFetch(`/marketplace/transactions/${row.id}/payment-session`, { method: 'POST' }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Unable to begin payment'); window.location.href = data.checkoutUrl; } catch (err) { setError(err.message); } }
  async function report(row) { try { const response = await adminFetch(`/marketplace/transactions/${row.id}/delivery-report`, { method: 'POST' }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Unable to report delivery'); setMessage('Delivery reported. The poster must confirm it before payout eligibility begins.'); await load(); } catch (err) { setError(err.message); } }
  async function confirm(row) { const key = crypto.randomUUID(); try { const response = await adminFetch(`/marketplace/transactions/${row.id}/confirm-delivery`, { method: 'POST', headers: { 'Idempotency-Key': key }, body: JSON.stringify({ idempotencyKey: key }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Unable to confirm delivery'); setMessage('Delivery confirmed. The payout is now subject to its risk-based availability window.'); await load(); } catch (err) { setError(err.message); } }
  const userId = typeof window === 'undefined' ? null : JSON.parse(localStorage.getItem('loadlyx_user') || 'null')?.id;
  const columns = [{ key: 'agreement', label: 'Agreement', render: (row) => <span><strong>{row.loadId}</strong><small>{new Date(row.createdAt).toLocaleDateString()}</small></span> }, { key: 'status', label: 'Status', render: (row) => <StatusBadge tone={row.status === 'PAID_OUT' ? 'success' : row.riskHold ? 'danger' : 'warning'}>{row.status}</StatusBadge> }, { key: 'gross', label: 'Gross', render: (row) => money(row.grossCents, row.currency) }, { key: 'fee', label: 'Loadlyx fee', render: (row) => money(row.platformFeeCents, row.currency) }, { key: 'net', label: 'Provider net', render: (row) => money(row.providerNetCents, row.currency) }, { key: 'action', label: 'Next action', render: (row) => <div className="action-row"><Link className="btn ghost" href={`/loads/${row.loadId}`}>Open load</Link>{row.posterId === userId && ['OFFER_ACCEPTED','PAYMENT_PENDING','PAYMENT_FAILED'].includes(row.status) ? <button className="btn" onClick={() => pay(row)}>Fund agreement</button> : null}{row.providerId === userId && ['FUNDED','IN_PROGRESS'].includes(row.status) ? <button className="btn" onClick={() => report(row)}>Report delivery</button> : null}{row.posterId === userId && ['DELIVERY_REPORTED','DELIVERY_CONFIRMATION_PENDING'].includes(row.status) ? <button className="btn" onClick={() => confirm(row)}>Confirm delivery</button> : null}</div> }];
  return <main className="container"><PageHeader eyebrow="Marketplace commerce" title="Agreements, payment, and payout" description="Accepted offer snapshots, customer funding, delivery confirmation, fee disclosure, risk holds, and provider payout remain visible in one lifecycle."/>{error ? <ErrorState message={error}/> : rows === null ? <LoadingState label="Loading marketplace transactions"/> : <section className="card"><DataTable columns={columns} rows={rows} emptyTitle="No accepted marketplace agreements" emptyDescription="Post a load or submit an eligible offer to begin."/></section>}{message ? <p className="success">{message}</p> : null}</main>;
}
