'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { adminFetch } from '@/lib/adminFetch';
import { clearSession, storeSession } from '@/lib/auth';
import { DataTable, Drawer, EmptyState, ErrorState, FilterBar, FormSection, Icon, LoadingState, PageHeader, StatusBadge } from '@/components/ui/LoadlyxUI';

const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4000/api';
const emptyLoad = { title: '', description: '', originCity: '', originRegion: '', originCountry: 'CA', destinationCity: '', destinationRegion: '', destinationCountry: 'CA', pickupDate: '', equipmentType: '', weightKg: '', budgetCents: '', postedForCustomer: false, customerName: '', customerEmail: '' };
async function authenticated(path, options) { const response = await adminFetch(path, options); const data = await response.json(); if (!response.ok) throw new Error(data?.error || 'Request failed'); return data; }
const money = (cents) => Number.isFinite(Number(cents)) ? new Intl.NumberFormat('en-CA', { style: 'currency', currency: 'CAD', maximumFractionDigits: 0 }).format(Number(cents) / 100) : 'Value not listed';
const bidCount = (load) => load.bidCount ?? load.bids?.length ?? 0;

export default function MarketplaceLoadBoardPage() {
  const [loads, setLoads] = useState([]); const [mine, setMine] = useState([]); const [form, setForm] = useState(emptyLoad); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [user, setUser] = useState(null); const [query, setQuery] = useState(''); const [showPost, setShowPost] = useState(false); const [selected, setSelected] = useState(null); const [view, setView] = useState('cards'); const [watchlist, setWatchlist] = useState([]);
  async function loadData() { setLoading(true); setError(''); try { const token = localStorage.getItem('token'); const response = await fetch(`${API_URL}/marketplace/loads`, { headers: token ? { Authorization: `Bearer ${token}` } : {} }); const publicRows = await response.json(); if (!response.ok) throw new Error(publicRows?.error || 'Unable to load marketplace'); setLoads(Array.isArray(publicRows) ? publicRows : []); if (token) setMine(await authenticated('/marketplace/loads/mine')); } catch (err) { setError(err.message); } finally { setLoading(false); } }
  useEffect(() => {
    let cancelled = false;
    try { setWatchlist(JSON.parse(localStorage.getItem('loadlyx_watchlist') || '[]')); } catch {}
    adminFetch('/auth/me').then(async (response) => {
      if (!response.ok) throw new Error('No active session');
      const data = await response.json();
      if (!cancelled) { storeSession({ user: data.user, tenantSlug: data.user?.tenantSlug || undefined }); setUser(data.user); }
    }).catch(() => { clearSession(); if (!cancelled) setUser(null); }).finally(() => { if (!cancelled) loadData(); });
    return () => { cancelled = true; };
  }, []);
  async function postLoad(event) { event.preventDefault(); try { await authenticated('/marketplace/loads', { method: 'POST', body: JSON.stringify({ ...form, pickupDate: new Date(form.pickupDate).toISOString(), weightKg: form.weightKg ? Number(form.weightKg) : undefined, budgetCents: form.budgetCents ? Number(form.budgetCents) : undefined }) }); setForm(emptyLoad); setShowPost(false); setMessage('Load posted to the marketplace.'); await loadData(); } catch (err) { setError(err.message); } }
  async function bid(load) { if (!user) { window.location.href = '/loadboard/login?next=/loadboard'; return; } if (load.isSimulated) { setMessage('Demo jobs are visual-only and cannot accept real bids.'); return; } const dollars = window.prompt('Bid amount in dollars:'); if (!dollars) return; const note = window.prompt('Message to the poster:') || ''; try { await authenticated(`/marketplace/loads/${load.id}/bids`, { method: 'POST', body: JSON.stringify({ amountCents: Math.round(Number(dollars) * 100), message: note }) }); setMessage('Bid submitted.'); await loadData(); } catch (err) { setError(err.message); } }
  function toggleWatch(loadId) { setWatchlist((current) => { const next = current.includes(loadId) ? current.filter((id) => id !== loadId) : [...current, loadId]; localStorage.setItem('loadlyx_watchlist', JSON.stringify(next)); return next; }); }
  const canBid = ['BROKER', 'CARRIER'].includes(user?.role); const canPost = Boolean(user);
  const commercialValue = (load) => user ? money(load.budgetCents || load.awardedAmountCents) : <Link href="/loadboard/login?next=/loadboard">Sign in to view price</Link>;
  const visible = useMemo(() => { const term = query.trim().toLowerCase(); return term ? loads.filter((load) => [load.title, load.originCity, load.destinationCity, load.equipmentType, load.status].some((value) => String(value || '').toLowerCase().includes(term))) : loads; }, [loads, query]);
  const columns = [
    { key: 'route', label: 'Route', render: (load) => <button type="button" className="btn ghost" onClick={() => setSelected(load)}>{load.originCity} → {load.destinationCity}</button> },
    { key: 'pickup', label: 'Pickup', render: (load) => load.pickupDate ? new Date(load.pickupDate).toLocaleDateString('en-CA') : 'Open' },
    { key: 'equipment', label: 'Equipment', render: (load) => load.equipmentType || 'Not specified' },
    { key: 'value', label: 'Offered value', render: commercialValue },
    { key: 'bids', label: 'Offers', render: bidCount },
    { key: 'status', label: 'Status', render: (load) => <StatusBadge tone={load.status === 'POSTED' ? 'success' : 'neutral'}>{load.status}</StatusBadge> },
    { key: 'action', label: 'Action', render: (load) => <div className="action-row"><button type="button" className="btn ghost" onClick={() => toggleWatch(load.id)}>{watchlist.includes(load.id) ? 'Saved' : 'Watch'}</button>{!user ? <Link className="btn" href="/loadboard/login?next=/loadboard">Sign in to bid</Link> : canBid && !load.isSimulated ? <button type="button" className="btn" onClick={() => bid(load)}>Bid</button> : null}</div> }
  ];

  return <main className="container grid lx-loadboard" style={{ gap: 24 }}>
    <PageHeader eyebrow="Live freight marketplace" title="Find the right move. Move it forward." description="Customers post loads. Verified brokers and carriers respond with offers. Sign in to view pricing, post, or bid." actions={canPost ? <button className="btn" type="button" onClick={() => setShowPost(!showPost)}>{showPost ? 'Close form' : 'Post a load'}</button> : <Link className="btn" href="/loadboard/login?next=/loadboard">Sign in to post</Link>} />
    {message ? <p className="success" role="status">{message}</p> : null}{error ? <ErrorState message={error} onRetry={loadData} /> : null}
    <FilterBar resultLabel={`${visible.length} available · ${watchlist.length} watched`} actions={<div className="action-row"><button type="button" className={`btn ghost ${view === 'table' ? 'active' : ''}`} onClick={() => setView('table')}>Table</button><button type="button" className={`btn ghost ${view === 'cards' ? 'active' : ''}`} onClick={() => setView('cards')}>Cards</button></div>}><label className="field"><span>Search loads</span><div className="input-with-icon"><Icon name="search" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="City, equipment, status, or title" /></div></label></FilterBar>
    {showPost ? <form className="grid" style={{ gap: 20 }} onSubmit={postLoad}><FormSection title="Route and schedule" description="Provide the essential movement details carriers need to evaluate the opportunity."><div className="grid grid-2"><label className="field"><span>Load title *</span><input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label className="field"><span>Pickup date *</span><input required type="datetime-local" value={form.pickupDate} onChange={(e) => setForm({ ...form, pickupDate: e.target.value })} /></label><label className="field"><span>Origin city *</span><input required value={form.originCity} onChange={(e) => setForm({ ...form, originCity: e.target.value })} /></label><label className="field"><span>Destination city *</span><input required value={form.destinationCity} onChange={(e) => setForm({ ...form, destinationCity: e.target.value })} /></label></div></FormSection><FormSection title="Load requirements" description="Add operational details so bids are comparable." actions={<button className="btn" type="submit">Publish load</button>}><div className="grid grid-3"><label className="field"><span>Equipment</span><input value={form.equipmentType} onChange={(e) => setForm({ ...form, equipmentType: e.target.value })} placeholder="Box truck, dry van…" /></label><label className="field"><span>Estimated weight (kg)</span><input type="number" min="0" value={form.weightKg} onChange={(e) => setForm({ ...form, weightKg: e.target.value })} /></label><label className="field"><span>Budget (cents)</span><input type="number" min="0" value={form.budgetCents} onChange={(e) => setForm({ ...form, budgetCents: e.target.value })} /></label></div><label className="field"><span>Description *</span><textarea required minLength={20} rows={5} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label>{user?.role === 'BROKER' ? <label className="checkbox-row"><input type="checkbox" checked={form.postedForCustomer} onChange={(e) => setForm({ ...form, postedForCustomer: e.target.checked })} /> Posting for a customer</label> : null}</FormSection></form> : null}
    {loading ? <LoadingState label="Loading marketplace opportunities" /> : view === 'table' ? <section className="card"><DataTable columns={columns} rows={visible} emptyTitle="No matching loads" emptyDescription="Try a broader search or post a new opportunity." /></section> : <section className="lx-load-layout"><div>{visible.length ? <div className="lx-load-grid">{visible.map((load) => <article className="lx-load-card" key={load.id}><div className="lx-load-card-top"><StatusBadge tone={load.status === 'POSTED' ? 'success' : 'neutral'}>{load.isSimulated ? 'DEMO JOB' : load.status}</StatusBadge><strong>{commercialValue(load)}</strong></div><h2>{load.title}</h2><div className="lx-route-line"><span><i />{load.originCity}<small>Pickup</small></span><b>→</b><span><i />{load.destinationCity}<small>Delivery</small></span></div><div className="lx-load-meta"><span><small>Pickup</small>{load.pickupDate ? new Date(load.pickupDate).toLocaleDateString('en-CA', { month: 'short', day: 'numeric' }) : 'Open'}</span><span><small>Equipment</small>{load.equipmentType || 'Not specified'}</span><span><small>Weight</small>{load.weightKg ? `${load.weightKg} kg` : 'Not listed'}</span><span><small>Offers</small>{bidCount(load)}</span></div><p>{load.description}</p><div className="lx-load-actions"><button className="btn ghost" type="button" onClick={() => toggleWatch(load.id)}>{watchlist.includes(load.id) ? 'Saved to watchlist' : 'Watch load'}</button><button className="btn secondary" type="button" onClick={() => setSelected(load)}>View details</button>{!user ? <Link className="btn" href="/login?next=/loadboard">Sign in to bid</Link> : canBid && !load.isSimulated ? <button className="btn" type="button" onClick={() => bid(load)}>Submit offer</button> : null}</div></article>)}</div> : <EmptyState title="No matching loads" description="Try a broader search or post a load to create a new marketplace opportunity." />}</div><aside className="lx-market-insight"><span className="lx-eyebrow">Marketplace guide</span><h3>Your role controls the next action.</h3><p>Customers can post their own loads. Brokers can manage customer opportunities. Eligible brokers and carriers can submit offers.</p><div><Icon name="check" /><span>Role-aware actions</span></div><div><Icon name="check" /><span>Local watchlist</span></div><div><Icon name="check" /><span>Protected offer access</span></div></aside></section>}
    {mine.length ? <section className="card"><h2>Loads connected to your account</h2><div className="lx-activity-row">{mine.map((load) => <button type="button" onClick={() => setSelected(load)} key={load.id}><StatusBadge>{load.status}</StatusBadge><strong>{load.title}</strong><span>{bidCount(load)} bids</span></button>)}</div></section> : null}
    <Drawer open={Boolean(selected)} title={selected?.title} description={selected ? `${selected.originCity} → ${selected.destinationCity}` : ''} onClose={() => setSelected(null)} footer={selected && !user ? <Link className="btn" href="/login?next=/loadboard">Sign in to view price and bid</Link> : selected && canBid && !selected.isSimulated ? <button className="btn" onClick={() => bid(selected)}>Submit offer</button> : null}>{selected ? <dl><div><dt>Budget</dt><dd>{commercialValue(selected)}</dd></div><div><dt>Equipment</dt><dd>{selected.equipmentType || 'Not specified'}</dd></div><div><dt>Weight</dt><dd>{selected.weightKg ? `${selected.weightKg} kg` : 'Not listed'}</dd></div><div><dt>Offers</dt><dd>{bidCount(selected)}</dd></div><div><dt>Description</dt><dd>{selected.description}</dd></div></dl> : null}</Drawer>
  </main>;
}
