'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { apiFetch } from '../../../lib/api';
import { getStoredUser } from '../../../lib/auth';
import { EmptyState, ErrorState, LoadingState, PageHeader, StatusBadge } from '../../../components/ui/LoadlyxUI';

const assignmentSteps = ['ASSIGNMENT_PENDING','DRIVER_ACCEPTED','EN_ROUTE_PICKUP','ARRIVED_PICKUP','LOADED','IN_TRANSIT','ARRIVED_DELIVERY','DELIVERED','POD_PENDING','COMPLETE'];
const nextStep = { ASSIGNMENT_PENDING:'DRIVER_ACCEPTED', DRIVER_ACCEPTED:'EN_ROUTE_PICKUP', EN_ROUTE_PICKUP:'ARRIVED_PICKUP', ARRIVED_PICKUP:'LOADED', LOADED:'IN_TRANSIT', IN_TRANSIT:'ARRIVED_DELIVERY', ARRIVED_DELIVERY:'DELIVERED', DELIVERED:'POD_PENDING', POD_PENDING:'COMPLETE' };
const roleCopy = {
  DRIVER:['Driver operations','Run todayâ€™s assigned load safely, one confirmed milestone at a time.'],
  CARRIER:['Carrier operations','Match capacity to profitable work, assign drivers, and execute every load.'],
  BROKER:['Broker operations','Post customer loads, locate eligible capacity, negotiate, and track execution.'],
  MARKETPLACE_USER:['Shipping workspace','Post your freight, compare providers, fund the agreement, and follow delivery.'],
  TENANT_ADMIN:['Freight operations','Connect your subscribed business tools to Loadlyx Connect marketplace execution.'],
  TENANT_STAFF:['Freight operations','Participate with the permissions granted by your tenant administrator.']
};

export default function LoadlyxConnectPage() {
  const [data,setData]=useState(null); const [error,setError]=useState(''); const [message,setMessage]=useState(''); const [truckOpen,setTruckOpen]=useState(false); const [truck,setTruck]=useState({truckId:'',equipmentType:'Dry van',trailerType:'53 ft',currentCity:'',availableAt:'',desiredDestination:'',maximumDeadheadKm:100,operatingRadiusKm:500,teamDriver:false});
  const user=getStoredUser(); const role=user?.role || 'MARKETPLACE_USER'; const copy=roleCopy[role] || roleCopy.TENANT_ADMIN;
  async function load(){setError('');setData(await apiFetch('/loadlyx-connect/workspace'));}
  useEffect(()=>{load().catch(e=>setError(e.message));},[]);
  const active=useMemo(()=>data?.loads?.filter(row=>row.assignment && row.assignment.status!=='COMPLETE')||[],[data]);
  async function createTruck(event){event.preventDefault();try{await apiFetch('/loadlyx-connect/trucks',{method:'POST',body:JSON.stringify({...truck,maximumDeadheadKm:Number(truck.maximumDeadheadKm),operatingRadiusKm:Number(truck.operatingRadiusKm),availableAt:new Date(truck.availableAt).toISOString()})});setMessage('Truck capacity is now available to eligible brokers.');setTruckOpen(false);await load();}catch(e){setError(e.message);}}
  async function updateAssignment(row,status){try{await apiFetch(`/loadlyx-connect/assignments/${row.assignment.id}/status`,{method:'PUT',body:JSON.stringify({status})});setMessage(`Status updated to ${status.replaceAll('_',' ').toLowerCase()}.`);await load();}catch(e){setError(e.message);}}
  async function consent(value){try{await apiFetch('/loadlyx-connect/driver/tracking-consent',{method:'PUT',body:JSON.stringify({consent:value})});setMessage(value?'Tracking consent recorded for active assigned loads only.':'Tracking consent revoked.');}catch(e){setError(e.message);}}
  async function shareLocation(loadId){if(!navigator.geolocation){setError('Location is not available on this device.');return;}navigator.geolocation.getCurrentPosition(async pos=>{try{await apiFetch(`/loadlyx-connect/loads/${loadId}/tracking`,{method:'POST',body:JSON.stringify({latitude:pos.coords.latitude,longitude:pos.coords.longitude,accuracyMeters:Math.round(pos.coords.accuracy)})});setMessage('Approximate location update sent for this active load.');}catch(e){setError(e.message);}},()=>setError('Location permission was not granted.'),{enableHighAccuracy:false,maximumAge:60000,timeout:10000});}
  return <main className="container grid lx-connect-workspace" style={{gap:24}}><PageHeader eyebrow="Loadlyx Connect" title={copy[0]} description={copy[1]} actions={<div className="action-row"><Link className="btn secondary" href="/loadboard">Find loads</Link>{['CARRIER','DRIVER','TENANT_ADMIN','TENANT_STAFF'].includes(role)?<button className="btn" onClick={()=>setTruckOpen(!truckOpen)}>{truckOpen?'Close capacity form':'Post a truck'}</button>:<Link className="btn" href="/quote">Post a load</Link>}</div>}/>{error?<ErrorState message={error}/>:null}{message?<p className="success" role="status">{message}</p>:null}{!data?<LoadingState label="Loading Loadlyx Connect operations"/>:<>
    <section className="lx-metric-grid"><article><span>Active loads</span><strong>{active.length}</strong><small>Assigned and executing</small></article><article><span>Available trucks</span><strong>{data.trucks?.filter(t=>t.status==='AVAILABLE').length||0}</strong><small>Visible to eligible brokers</small></article><article><span>Saved searches</span><strong>{data.savedSearches?.length||0}</strong><small>Alerts remain account-scoped</small></article><article><span>Role</span><strong style={{fontSize:'1.25rem'}}>{role.replaceAll('_',' ')}</strong><small>Backend-enforced access</small></article></section>
    {truckOpen?<form className="card grid" id="trucks" onSubmit={createTruck} style={{gap:16}}><div className="panel-header"><div><span className="lx-eyebrow">Available capacity</span><h2>Post a truck</h2><p className="muted">Exact coordinates are never exposed on public truck search.</p></div></div><div className="grid two"><label>Truck ID<input required value={truck.truckId} onChange={e=>setTruck({...truck,truckId:e.target.value})}/></label><label>Current city<input required value={truck.currentCity} onChange={e=>setTruck({...truck,currentCity:e.target.value})}/></label><label>Equipment<input required value={truck.equipmentType} onChange={e=>setTruck({...truck,equipmentType:e.target.value})}/></label><label>Trailer<input value={truck.trailerType} onChange={e=>setTruck({...truck,trailerType:e.target.value})}/></label><label>Available date/time<input required type="datetime-local" value={truck.availableAt} onChange={e=>setTruck({...truck,availableAt:e.target.value})}/></label><label>Desired destination<input value={truck.desiredDestination} onChange={e=>setTruck({...truck,desiredDestination:e.target.value})}/></label><label>Maximum deadhead (km)<input type="number" min="1" value={truck.maximumDeadheadKm} onChange={e=>setTruck({...truck,maximumDeadheadKm:e.target.value})}/></label><label>Operating radius (km)<input type="number" min="1" value={truck.operatingRadiusKm} onChange={e=>setTruck({...truck,operatingRadiusKm:e.target.value})}/></label></div><label className="checkbox-row"><input type="checkbox" checked={truck.teamDriver} onChange={e=>setTruck({...truck,teamDriver:e.target.checked})}/> Team-driver capacity</label><button className="btn">Publish capacity</button></form>:null}
    {role==='DRIVER'?<section className="card" id="tracking"><div className="panel-header"><div><span className="lx-eyebrow">Consent and safety</span><h2>Active-load tracking</h2><p className="muted">Tracking operates only during an accepted assignment. Avoid interacting while the vehicle is moving.</p></div><div className="action-row"><button className="btn secondary" onClick={()=>consent(true)}>Allow active-load tracking</button><button className="btn ghost" onClick={()=>consent(false)}>Revoke</button></div></div></section>:null}
    <section id="loads"><div className="panel-header"><div><span className="lx-eyebrow">Execution</span><h2>{role==='DRIVER'?'My assigned loads':'Connected loads'}</h2></div></div>{data.loads?.length?<div className="lx-load-grid">{data.loads.map(row=><article className="card lx-one-load" key={row.id}><div className="panel-header"><StatusBadge>{row.assignment?.status||row.status}</StatusBadge><small>{new Date(row.pickupDate).toLocaleDateString('en-CA')}</small></div><h3>{row.title}</h3><p><strong>{row.originCity}</strong> â†’ <strong>{row.destinationCity}</strong></p>{row.assignment?<><div className="lx-step-strip" aria-label="Load execution progress">{assignmentSteps.map(step=><i key={step} className={assignmentSteps.indexOf(step)<=assignmentSteps.indexOf(row.assignment.status)?'done':''} title={step}/>)}</div>{role==='DRIVER'&&nextStep[row.assignment.status]?<div className="action-row"><button className="btn lx-btn-lg" onClick={()=>updateAssignment(row,nextStep[row.assignment.status])}>Confirm {nextStep[row.assignment.status].replaceAll('_',' ').toLowerCase()}</button>{!['ASSIGNMENT_PENDING','DRIVER_DECLINED','COMPLETE'].includes(row.assignment.status)?<button className="btn secondary" onClick={()=>shareLocation(row.id)}>Send location update</button>:null}</div>:null}</>:<p className="muted">No driver assignment yet.</p>}<div className="action-row"><Link className="btn ghost" href={`/loads/${row.id}`}>Open load</Link><Link className="btn ghost" href="/app/marketplace-offers">Offers</Link></div></article>)}</div>:<EmptyState title="No loads connected to this account" description="Post a load or find an eligible marketplace opportunity." actionHref="/loadboard" actionLabel="Open load board"/>}</section>
    {data.trucks?.length?<section id="trucks"><div className="panel-header"><div><span className="lx-eyebrow">Capacity</span><h2>My trucks</h2></div></div><div className="lx-module-grid">{data.trucks.map(t=><article className="lx-module-card" key={t.id}><StatusBadge>{t.status}</StatusBadge><h3>{t.truckId} Â· {t.equipmentType}</h3><p>{t.currentCity} â†’ {t.desiredDestination||'Open destination'}</p><small>Available {new Date(t.availableAt).toLocaleString('en-CA')}</small></article>)}</div></section>:null}
    <section className="card" id="documents"><div className="panel-header"><div><span className="lx-eyebrow">Documents and communication</span><h2>Secure load record</h2><p className="muted">BOL, POD, rate confirmations, invoices, photos, damage records, insurance, and authority documents remain participant-only with upload audit history.</p></div><Link className="btn secondary" href="/resources">Document guide</Link></div></section>
  </>}</main>;
}

