'use client';

import { useEffect, useMemo, useState } from 'react';
import { apiFetch } from '../../../lib/api';
import { DataTable, Drawer, ErrorState, FilterBar, LoadingState, PageHeader, StatCard, StatusBadge } from '../../../components/ui/LoadlyxUI';
import { Timeline } from '../../../components/ui/InteractiveUI';

const statuses = ['PENDING','POSTED','BOOKED','COMPLETED','CANCELED'];
const tone = (status) => status === 'COMPLETED' ? 'success' : status === 'CANCELED' ? 'danger' : status === 'BOOKED' ? 'blue' : 'warning';
const date = (value, options = {}) => value ? new Date(value).toLocaleDateString('en-CA', options) : 'Flexible';

export default function DispatchPage() {
  const [loads, setLoads] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [status, setStatus] = useState('ALL'); const [query, setQuery] = useState(''); const [view, setView] = useState('board'); const [selected, setSelected] = useState(null); const [saving, setSaving] = useState('');
  async function load() { setLoading(true); setError(''); try { setLoads(await apiFetch('/loads')); } catch (err) { setError(err.message); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  const visible = useMemo(() => loads.filter((row) => (status === 'ALL' || row.status === status) && `${row.originCity} ${row.destinationCity} ${row.equipmentType} ${row.status}`.toLowerCase().includes(query.toLowerCase())), [loads, status, query]);
  async function updateStatus(row, next) { setSaving(row.id); setError(''); try { await apiFetch(`/loads/${row.id}`, { method: 'PUT', body: JSON.stringify({ status: next, notes: row.summary || '' }) }); setMessage(`Load moved to ${next}.`); await load(); } catch (err) { setError(err.message); } finally { setSaving(''); } }
  const active = loads.filter((row) => !['COMPLETED','CANCELED'].includes(row.status)); const scheduled = loads.filter((row) => row.pickupDate); const open = loads.filter((row) => ['PENDING','POSTED'].includes(row.status)); const unassigned = loads.filter((row) => !row.carrierId && !row.assignedCarrier);
  const columns = [
    { key: 'status', label: 'Status', render: (row) => <StatusBadge tone={tone(row.status)}>{row.status}</StatusBadge> },
    { key: 'route', label: 'Route', render: (row) => <button type="button" className="lx-text-button" onClick={() => setSelected(row)}><strong>{row.originCity || 'Origin TBD'} → {row.destinationCity || 'Destination TBD'}</strong><span>{row.equipmentType || 'Equipment not assigned'}</span></button> },
    { key: 'pickup', label: 'Pickup', render: (row) => date(row.pickupDate, { month: 'short', day: 'numeric', year: 'numeric' }) },
    { key: 'weight', label: 'Weight', render: (row) => row.estimatedWeightKg ? `${Number(row.estimatedWeightKg).toFixed(0)} kg` : 'TBD' },
    { key: 'assignment', label: 'Assignment', render: (row) => row.assignedCarrier?.companyName || row.carrier?.companyName || (row.carrierId ? 'Carrier assigned' : <StatusBadge tone="warning">Unassigned</StatusBadge>) },
    { key: 'action', label: 'Update', render: (row) => <select aria-label={`Update ${row.originCity} to ${row.destinationCity} status`} value={row.status} disabled={saving === row.id} onChange={(event) => updateStatus(row, event.target.value)}>{statuses.map((value) => <option key={value}>{value}</option>)}</select> }
  ];
  const dated = [...visible].filter((row) => row.pickupDate).sort((a, b) => new Date(a.pickupDate) - new Date(b.pickupDate));

  return <main className="container"><PageHeader eyebrow="Dispatch intelligence" title="Load operations" description="See unassigned work first, coordinate the schedule, review routes and move jobs through existing authorized status transitions." actions={<div className="action-row">{[['board','Board'],['calendar','Calendar'],['routes','Routes']].map(([key,label]) => <button type="button" key={key} className={`btn ghost ${view === key ? 'active' : ''}`} onClick={() => setView(key)}>{label}</button>)}</div>} />
    {message ? <p className="success" role="status">{message}</p> : null}{error ? <ErrorState message={error} onRetry={load} /> : loading ? <LoadingState label="Loading dispatch board" /> : <>
      <section className="lx-stat-grid"><StatCard label="Active loads" value={active.length} detail="Current operating workload" icon="route" /><StatCard label="Scheduled pickups" value={scheduled.length} detail="Loads with pickup dates" tone="green" icon="check" /><StatCard label="Open queue" value={open.length} detail="Pending or posted work" tone="orange" icon="alert" /><StatCard label="Unassigned" value={unassigned.length} detail="Assignment review required" tone="purple" icon="users" /></section>
      {unassigned.length ? <section className="lx-attention-panel" style={{ marginTop: 20 }}><div><span className="lx-eyebrow">Requires attention</span><h2>{unassigned.length} load{unassigned.length === 1 ? '' : 's'} need an assignment.</h2><p>Review the routes and timing before the pickup window is at risk.</p></div><div className="lx-attention-actions">{unassigned.slice(0, 4).map((row) => <button type="button" key={row.id} onClick={() => setSelected(row)}><span><strong>{row.originCity || 'Origin TBD'} → {row.destinationCity || 'Destination TBD'}</strong><small>{date(row.pickupDate)}</small></span><b>Review</b></button>)}</div></section> : null}
      <section className="lx-panel" style={{ marginTop: 20 }}><FilterBar resultLabel={`${visible.length} loads`}><label className="field"><span>Search dispatch</span><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Route, equipment or status" /></label><label className="field"><span>Status</span><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="ALL">All statuses</option>{statuses.map((value) => <option key={value}>{value}</option>)}</select></label></FilterBar>
        {view === 'board' ? <DataTable columns={columns} rows={visible} emptyTitle="No dispatch work" emptyDescription="Booked and marketplace loads will appear here for operational review." /> : null}
        {view === 'calendar' ? <div className="lx-dispatch-calendar">{dated.length ? dated.map((row) => <button type="button" key={row.id} onClick={() => setSelected(row)}><time><strong>{new Date(row.pickupDate).toLocaleDateString('en-CA', { day: '2-digit' })}</strong><span>{new Date(row.pickupDate).toLocaleDateString('en-CA', { month: 'short' })}</span></time><div><StatusBadge tone={tone(row.status)}>{row.status}</StatusBadge><h3>{row.originCity} → {row.destinationCity}</h3><p>{row.equipmentType || 'Equipment TBD'} · {row.carrierId ? 'Assigned' : 'Unassigned'}</p></div></button>) : <p className="muted">No scheduled pickup dates are available.</p>}</div> : null}
        {view === 'routes' ? <div className="lx-route-network" aria-label="Route overview based on current load records"><div className="lx-route-network-grid" aria-hidden="true" />{visible.length ? visible.map((row, index) => <button type="button" key={row.id} className="lx-route-path" style={{ '--route-index': index % 6 }} onClick={() => setSelected(row)}><span>{row.originCity || 'Origin TBD'}</span><i /><b>→</b><i /><span>{row.destinationCity || 'Destination TBD'}</span><small>{date(row.pickupDate)} · {row.status}</small></button>) : <p>No route data is available.</p>}<aside><strong>Operational route view</strong><p>Routes come from current load records. Exact live vehicle locations are not displayed without an authorized location provider.</p></aside></div> : null}
      </section>
    </>}
    <Drawer open={Boolean(selected)} title={selected ? `${selected.originCity || 'Origin TBD'} → ${selected.destinationCity || 'Destination TBD'}` : ''} description={selected ? `Load ${selected.id}` : ''} onClose={() => setSelected(null)}>{selected ? <div className="grid" style={{ gap: 20 }}><section className="lx-detail-grid"><div><span>Status</span><StatusBadge tone={tone(selected.status)}>{selected.status}</StatusBadge></div><div><span>Pickup</span><strong>{date(selected.pickupDate)}</strong></div><div><span>Equipment</span><strong>{selected.equipmentType || 'Not assigned'}</strong></div><div><span>Weight</span><strong>{selected.estimatedWeightKg ? `${Number(selected.estimatedWeightKg).toFixed(0)} kg` : 'TBD'}</strong></div><div><span>Carrier</span><strong>{selected.assignedCarrier?.companyName || selected.carrier?.companyName || 'Unassigned'}</strong></div><div><span>Exception</span><strong>{selected.exception || 'None recorded'}</strong></div></section><section><h3>Job timeline</h3><Timeline items={[selected.createdAt ? { title: 'Load created', time: date(selected.createdAt), icon: 'route' } : null, { title: `Current status: ${selected.status}`, description: selected.carrierId ? 'A carrier assignment is recorded.' : 'Carrier assignment is still required.', time: selected.updatedAt ? date(selected.updatedAt) : undefined, icon: selected.carrierId ? 'check' : 'alert' }, selected.pickupDate ? { title: 'Scheduled pickup', time: date(selected.pickupDate), icon: 'chart' } : null].filter(Boolean)} /></section></div> : null}</Drawer>
  </main>;
}
