'use client';

import { useEffect, useState } from 'react';
import { adminFetch } from '@/lib/adminFetch';

async function request(path, options) { const response = await adminFetch(path, options); const data = await response.json(); if (!response.ok) throw new Error(data?.error || 'Request failed'); return data; }
const MODULES = ['CRM','DISPATCH','MARKETPLACE','BROKER','CARRIER','STORE','CUSTOMER','ADMIN','SUPPORT'];

export default function AiAdminPage() {
  const [tenants, setTenants] = useState([]); const [configs, setConfigs] = useState([]); const [usage, setUsage] = useState({ totals: {} }); const [message, setMessage] = useState('');
  async function load() { try { const [tenantRows, configRows, usageData] = await Promise.all([request('/platform-admin/tenants'), request('/ai/admin/configs'), request('/ai/admin/usage')]); setTenants(tenantRows); setConfigs(configRows); setUsage(usageData); } catch (error) { setMessage(error.message); } }
  useEffect(() => { load(); }, []);
  function configFor(tenant) { return configs.find((config) => config.tenantId === tenant.id) || { enabled: false, monthlyRequestLimit: 100, allowedModules: [] }; }
  async function save(tenant, config) { const reason = window.prompt('Reason for changing tenant AI access:'); if (!reason) return; try { await request(`/ai/admin/configs/${tenant.id}`, { method: 'PUT', body: JSON.stringify({ enabled: config.enabled, monthlyRequestLimit: Number(config.monthlyRequestLimit), allowedModules: config.allowedModules, reason }) }); setMessage('AI access updated and audited.'); await load(); } catch (error) { setMessage(error.message); } }
  function updateLocal(tenantId, changes) { setConfigs((current) => { const existing = current.find((item) => item.tenantId === tenantId); return existing ? current.map((item) => item.tenantId === tenantId ? { ...item, ...changes } : item) : [...current, { tenantId, enabled: false, monthlyRequestLimit: 100, allowedModules: [], ...changes }]; }); }
  return <main className="container grid" style={{ gap: 24 }}><section className="card"><h1>AI Operations</h1><p className="muted">Control reusable AI modules, tenant limits, usage, and costs. Provider credentials and model selection remain server-side environment settings.</p>{message ? <p className="success">{message}</p> : null}</section><section className="grid grid-3"><div className="card"><span className="muted">Requests logged</span><h2>{usage.totals?._count || 0}</h2></div><div className="card"><span className="muted">Input tokens</span><h2>{usage.totals?._sum?.inputTokens || 0}</h2></div><div className="card"><span className="muted">Output tokens</span><h2>{usage.totals?._sum?.outputTokens || 0}</h2></div></section><section className="card"><h2>Tenant AI access</h2><div className="grid">{tenants.map((tenant) => { const config = configFor(tenant); return <div className="card" key={tenant.id}><div className="row-between"><div><strong>{tenant.name}</strong><div className="muted small">{tenant.slug}.loadlyx.com</div></div><label className="checkbox-row"><input type="checkbox" checked={config.enabled} onChange={(event) => updateLocal(tenant.id, { enabled: event.target.checked })} /> Enabled</label></div><div className="field"><label>Monthly request limit</label><input type="number" min="0" value={config.monthlyRequestLimit} onChange={(event) => updateLocal(tenant.id, { monthlyRequestLimit: event.target.value })} /></div><div className="action-row" style={{ flexWrap: 'wrap' }}>{MODULES.map((module) => <label className="checkbox-row" key={module}><input type="checkbox" checked={(config.allowedModules || []).includes(module)} onChange={(event) => updateLocal(tenant.id, { allowedModules: event.target.checked ? [...(config.allowedModules || []), module] : (config.allowedModules || []).filter((item) => item !== module) })} /> {module}</label>)}</div><button className="btn" onClick={() => save(tenant, config)}>Save AI access</button></div>; })}</div></section></main>;
}
