import crypto from 'crypto';

export const SERVICE_TYPES=['FACTORING','QUICK_PAY','FUEL_CARD','FUEL_OPTIMIZATION','AUTHORITY','INSURANCE','COMPLIANCE'];
export const SERVICE_LABELS={FACTORING:'Loadlyx Capital',QUICK_PAY:'Quick Pay',FUEL_CARD:'Fuel cards',FUEL_OPTIMIZATION:'Fuel optimization',AUTHORITY:'Operating authority',INSURANCE:'Insurance',COMPLIANCE:'Loadlyx Verify'};
export const DEFAULT_SERVICE_STATUS={FACTORING:'PARTNER_REQUIRED',QUICK_PAY:'CONFIGURATION_REQUIRED',FUEL_CARD:'PARTNER_REQUIRED',FUEL_OPTIMIZATION:'AVAILABLE',AUTHORITY:'PARTNER_REQUIRED',INSURANCE:'PARTNER_REQUIRED',COMPLIANCE:'CONFIGURATION_REQUIRED'};

export function serviceCatalogue(partners=[]){return SERVICE_TYPES.map(type=>{const configured=partners.find(p=>p.serviceType===type&&p.enabled);return{type,label:SERVICE_LABELS[type],status:configured?.status||DEFAULT_SERVICE_STATUS[type],partner:configured?{id:configured.id,name:configured.name,providerKey:configured.providerKey}:null,disclaimer:['FACTORING','FUEL_CARD','AUTHORITY','INSURANCE'].includes(type)?'Provided by an independent configured partner. Loadlyx is not the regulated provider.':type==='QUICK_PAY'?'Subject to configured payment-provider eligibility and disclosed fees.':'Operational estimate or platform workflow; verify requirements with qualified providers.'}})}
export function calculateServiceQuote({invoiceAmountCents,advanceBasisPoints=10000,feeBasisPoints=0,fixedFeeCents=0}){const invoice=Number(invoiceAmountCents);if(!Number.isSafeInteger(invoice)||invoice<=0)throw new Error('Positive invoice amount is required');if(advanceBasisPoints<0||advanceBasisPoints>10000||feeBasisPoints<0||feeBasisPoints>10000)throw new Error('Basis points must be between 0 and 10000');const advance=Math.floor(invoice*advanceBasisPoints/10000);const fee=Math.floor(invoice*feeBasisPoints/10000)+Number(fixedFeeCents||0);if(fee>=advance)throw new Error('Service fee cannot consume the advance');return{invoiceAmountCents:invoice,advanceBasisPoints,advanceAmountCents:advance,feeCents:fee,netAmountCents:advance-fee,remainderCents:invoice-advance,requiresAcceptance:true}}
export function calculateFuelEstimate({distanceKm,fuelEconomyLPer100Km,fuelPricePerLitre,detourKm=0}){for(const value of[distanceKm,fuelEconomyLPer100Km,fuelPricePerLitre,detourKm])if(!Number.isFinite(Number(value))||Number(value)<0)throw new Error('Fuel inputs must be non-negative numbers');const totalKm=Number(distanceKm)+Number(detourKm);const litres=totalKm*Number(fuelEconomyLPer100Km)/100;return{distanceKm:Number(distanceKm),detourKm:Number(detourKm),totalKm:Number(totalKm.toFixed(1)),expectedLitres:Number(litres.toFixed(2)),estimatedFuelCostCents:Math.round(litres*Number(fuelPricePerLitre)*100),livePrice:false,safetyNotice:Number(detourKm)>50?'Detour exceeds the default safe-planning threshold and requires operator review':'Route estimate only; confirm safe and legal fueling access'}}
export function insuranceStatus(policy,now=new Date()){const expiry=new Date(policy.expiryDate);if(expiry<=now)return'RESTRICTED';if(expiry.getTime()-now.getTime()<=30*86400000)return'EXPIRING';return policy.status==='VERIFIED'?'VERIFIED':'REVIEW'}
export function qualificationResult({identityVerified,businessVerified,authorityStatus,insuranceStatus,equipmentEligible,serviceAreaEligible,trustScore=0,suspended=false,certificationsComplete=true}){const checks={identity:Boolean(identityVerified),business:Boolean(businessVerified),authority:authorityStatus==='VERIFIED',insurance:insuranceStatus==='VERIFIED',equipment:Boolean(equipmentEligible),serviceArea:Boolean(serviceAreaEligible),trust:Number(trustScore)>=60,notSuspended:!suspended,certifications:Boolean(certificationsComplete)};const failed=Object.entries(checks).filter(([,ok])=>!ok).map(([key])=>key);return{eligible:failed.length===0,status:suspended?'RESTRICTED':failed.length?'INFORMATION_REQUIRED':'VERIFIED',checks,failed,explanation:failed.length?`Requirements outstanding: ${failed.join(', ')}`:'Carrier meets configured qualification requirements'}}
export function protectPolicyNumber(value){const normalized=String(value||'').replace(/\s/g,'');if(normalized.length<4)throw new Error('Policy number must contain at least four characters');return{encrypted:crypto.createHash('sha256').update(normalized).digest('hex'),last4:normalized.slice(-4)}}
