function hideCommercialTerms(load) {
  const bids = Array.isArray(load.bids) ? load.bids : [];
  return {
    ...load,
    budgetCents: null,
    awardedAmountCents: null,
    bidCount: bids.length,
    bids: []
  };
}

export function simulationEventToLoad(event, authenticated = false) {
  const payload = event.payloadJson || {};
  const amountCents = Number.isInteger(payload.amountCents) ? payload.amountCents : 85000 + (Number(payload.sequence || 1) * 12500);
  const row = {
    id: `simulation:${event.id}`,
    title: payload.title || `${payload.origin || 'Winnipeg'} to ${payload.destination || 'Regina'} moving opportunity`,
    description: payload.description || 'Demonstration marketplace job generated by Loadlyx Demo Mode. It cannot create a real charge, payout, or booking.',
    originCity: payload.origin || 'Winnipeg',
    originRegion: payload.originRegion || '',
    originCountry: payload.originCountry || 'CA',
    destinationCity: payload.destination || 'Regina',
    destinationRegion: payload.destinationRegion || '',
    destinationCountry: payload.destinationCountry || 'CA',
    pickupDate: payload.pickupDate || event.createdAt,
    equipmentType: payload.equipmentType || 'Moving truck',
    weightKg: payload.weightKg || null,
    budgetCents: amountCents,
    awardedAmountCents: null,
    status: 'POSTED',
    bids: [],
    bidCount: Number(payload.bidCount || 0),
    isSimulated: true,
    watermark: payload.watermark || 'DEMO DATA',
    createdAt: event.createdAt
  };
  return authenticated ? row : hideCommercialTerms(row);
}

export function presentMarketplaceLoads({ loads = [], simulationEvents = [], authenticated = false }) {
  const realLoads = loads.map((load) => authenticated ? { ...load, bidCount: load.bids?.length || 0 } : hideCommercialTerms(load));
  const simulatedLoads = simulationEvents.map((event) => simulationEventToLoad(event, authenticated));
  return [...simulatedLoads, ...realLoads];
}
