import { Router } from 'express';
import { z } from 'zod';
import { prisma } from '../db/prisma.js';
import { requireAuth } from '../middleware/requireauth.js';
import { requireEntitlement } from '../middleware/requireEntitlement.js';

const router = Router();
router.get('/', async (req, res, next) => { try { const tenantId = req.tenant?.id || req.user?.tenantId; if (!tenantId) return res.status(400).json({ error: 'Tenant context required' }); return res.json(await prisma.productCollection.findMany({ where: { tenantId, isActive: true }, include: { products: { include: { product: { include: { images: { orderBy: { position: 'asc' } }, variants: true } } }, orderBy: { position: 'asc' } } }, orderBy: { name: 'asc' } })); } catch (error) { return next(error); } });
router.use(requireAuth, requireEntitlement('products'));
router.post('/', async (req, res, next) => { try { const tenantId = req.user.tenantId; if (!tenantId) return res.status(403).json({ error: 'Tenant account required' }); const input = z.object({ name: z.string().min(2).max(160), slug: z.string().regex(/^[a-z0-9-]+$/), description: z.string().max(2000).optional(), productIds: z.array(z.string()).max(500).default([]) }).parse(req.body); const owned = await prisma.product.count({ where: { tenantId, id: { in: input.productIds } } }); if (owned !== new Set(input.productIds).size) return res.status(400).json({ error: 'A selected product does not belong to this tenant' }); const row = await prisma.$transaction(async (tx) => { const collection = await tx.productCollection.create({ data: { tenantId, name: input.name, slug: input.slug, description: input.description } }); if (input.productIds.length) await tx.productCollectionItem.createMany({ data: input.productIds.map((productId, position) => ({ collectionId: collection.id, productId, position })) }); return tx.productCollection.findUnique({ where: { id: collection.id }, include: { products: true } }); }); return res.status(201).json(row); } catch (error) { return next(error); } });
router.put('/:id', async (req, res, next) => { try { const tenantId = req.user.tenantId; const collection = await prisma.productCollection.findFirst({ where: { id: req.params.id, tenantId } }); if (!collection) return res.status(404).json({ error: 'Collection not found' }); const input = z.object({ name: z.string().min(2).max(160), slug: z.string().regex(/^[a-z0-9-]+$/), description: z.string().max(2000).optional().nullable(), isActive: z.boolean().default(true), productIds: z.array(z.string()).max(500).default([]) }).parse(req.body); const owned = await prisma.product.count({ where: { tenantId, id: { in: input.productIds } } }); if (owned !== new Set(input.productIds).size) return res.status(400).json({ error: 'A selected product does not belong to this tenant' }); return res.json(await prisma.$transaction(async (tx) => { await tx.productCollection.update({ where: { id: collection.id }, data: { name: input.name, slug: input.slug, description: input.description, isActive: input.isActive } }); await tx.productCollectionItem.deleteMany({ where: { collectionId: collection.id } }); if (input.productIds.length) await tx.productCollectionItem.createMany({ data: input.productIds.map((productId, position) => ({ collectionId: collection.id, productId, position })) }); return tx.productCollection.findUnique({ where: { id: collection.id }, include: { products: true } }); })); } catch (error) { return next(error); } });
router.delete('/:id', async (req, res, next) => { try { const row = await prisma.productCollection.findFirst({ where: { id: req.params.id, tenantId: req.user.tenantId } }); if (!row) return res.status(404).json({ error: 'Collection not found' }); await prisma.productCollection.delete({ where: { id: row.id } }); return res.status(204).end(); } catch (error) { return next(error); } });
export default router;
