import { Router } from 'express';
import { z } from 'zod';
import { prisma } from '../db/prisma.js';
import { requireAuth } from '../middleware/requireauth.js';
import { DATA_SOURCES, INTELLIGENCE_MODEL, buildBenchmark, buildMarketConditions, buildRateIntelligence, calculateDeadhead, findBackhaulOpportunities, negotiationRecommendation, planMultiLegTrip, rankLoadsForTruck, rankTrucksForLoad } from '../services/freightIntelligence.js';

const router = Router(); router.use(requireAuth);
const PLATFORM = new Set(['SUPER_ADMIN','PLATFORM_ADMIN','ADMIN','SUPPORT']);
const INTELLIGENCE_ROLES = new Set(['BROKER','CARRIER','TENANT_ADMIN','TENANT_STAFF','SUPER_ADMIN','PLATFORM_ADMIN','ADMIN','SUPPORT']);
const costsSchema = z.object({ costPerKm:z.number().nonnegative().optional(), fuelPricePerLitre:z.number().nonnegative().optional(), fuelEconomyLPer100Km:z.number().nonnegative().optional(), driverCostPerKm:z.number().nonnegative().optional(), maintenancePerKm:z.number().nonnegative().optional() }).default({});

function assertRole(req, res) { if (!INTELLIGENCE_ROLES.has(req.user.role)) { res.status(403).json({error:'Freight intelligence access requires a broker, carrier, tenant, or platform operations role'}); return false; } return true; }
function carrierScope(user) { return user.tenantId || user.userId; }
function tenantFilter(user) { return PLATFORM.has(user.role) ? {} : user.tenantId ? { tenantId:user.tenantId } : { userId:user.userId }; }
function sanitize(value) { return JSON.parse(JSON.stringify(value, (key,item) => ['password','token','secret'].some(term=>key.toLowerCase().includes(term)) ? undefined : item)); }
async function record(req,{feature,entityType,entityId,input,recommendation}) { return prisma.freightIntelligenceRecommendation.create({data:{tenantId:req.user.tenantId||null,userId:req.user.userId,feature,entityType,entityId:entityId||null,modelName:INTELLIGENCE_MODEL.name,modelVersion:INTELLIGENCE_MODEL.version,dataSource:DATA_SOURCES.network,inputSnapshot:sanitize(input),recommendation:sanitize(recommendation),confidence:String(recommendation.confidence||0),explanation:sanitize(recommendation.reasons||recommendation.explanation||[]),approvalRequired:true}}); }
async function networkRows({origin,destination,equipment,since}) { const loads=await prisma.marketplaceLoad.findMany({where:{...(origin?{originCity:{equals:origin,mode:'insensitive'}}:{}),...(destination?{destinationCity:{equals:destination,mode:'insensitive'}}:{}),...(equipment?{equipmentType:{equals:equipment,mode:'insensitive'}}:{}),...(since?{createdAt:{gte:since}}:{})},include:{bids:{where:{status:'ACCEPTED'}}},take:500}); return loads; }
function observations(loads) { return loads.flatMap(load=>[{amountCents:load.budgetCents,kind:'POSTED',source:DATA_SOURCES.network,occurredAt:load.createdAt},...load.bids.map(bid=>({amountCents:bid.amountCents,kind:'ACCEPTED',source:DATA_SOURCES.network,occurredAt:bid.acceptedAt||bid.updatedAt}))]).filter(row=>row.amountCents); }

router.get('/overview',async(req,res,next)=>{try{if(!assertRole(req,res))return;const now=new Date();const [loads,trucks,recommendations]=await Promise.all([prisma.marketplaceLoad.findMany({where:{status:{in:['POSTED','BIDDING','AWARDED','FUNDED','PICKED_UP','IN_TRANSIT']},...(req.user.role==='BROKER'?{OR:[{brokerId:req.user.userId},{posterId:req.user.userId},{status:{in:['POSTED','BIDDING']}}]}:{})},include:{bids:{where:{status:'ACCEPTED'}}},take:250}),prisma.truckAvailability.findMany({where:{status:'AVAILABLE',...(req.user.role==='CARRIER'?{carrierId:carrierScope(req.user)}:{})},take:250}),prisma.freightIntelligenceRecommendation.findMany({where:tenantFilter(req.user),orderBy:{createdAt:'desc'},take:20})]);const conditions=buildMarketConditions({loads,trucks,accepted:loads.flatMap(load=>load.bids.map(bid=>({amountCents:bid.amountCents})))});return res.json({model:INTELLIGENCE_MODEL,dataSources:{network:{label:DATA_SOURCES.network,description:'Loadlyx first-party loads, trucks, offers, assignments, and completed transactions'},thirdParty:{label:DATA_SOURCES.thirdParty,enabled:false,description:'No approved third-party freight-rate dataset is configured'}},conditions,counts:{activeLoads:loads.length,availableTrucks:trucks.length,recommendations:recommendations.length},recommendations,generatedAt:now});}catch(error){next(error);}});

router.post('/match/load/:loadId',async(req,res,next)=>{try{if(!assertRole(req,res))return;const input=z.object({costs:costsSchema,deadheadByTruck:z.record(z.number().nonnegative()).default({})}).parse(req.body||{});const [load,trucks]=await Promise.all([prisma.marketplaceLoad.findUnique({where:{id:req.params.loadId}}),prisma.truckAvailability.findMany({where:{status:'AVAILABLE'},take:250})]);if(!load)return res.status(404).json({error:'Load not found'});if(!PLATFORM.has(req.user.role)&&req.user.role==='BROKER'&&load.posterId!==req.user.userId&&load.brokerId!==req.user.userId)return res.status(403).json({error:'Broker access to this load is required'});const options=Object.fromEntries(trucks.map(truck=>[truck.id,{deadheadKm:input.deadheadByTruck[truck.id],costs:input.costs}]));const ranking=rankTrucksForLoad(load,trucks,options);const recommendation={confidence:ranking[0]?.confidence||0,ranking,requiresHumanApproval:true,dataLabel:DATA_SOURCES.network};const audit=await record(req,{feature:'LOAD_TO_TRUCK_MATCH',entityType:'MARKETPLACE_LOAD',entityId:load.id,input,recommendation});return res.json({...recommendation,recommendationId:audit.id});}catch(error){next(error);}});
router.post('/match/truck/:truckId',async(req,res,next)=>{try{if(!assertRole(req,res))return;const input=z.object({costs:costsSchema,deadheadByLoad:z.record(z.number().nonnegative()).default({})}).parse(req.body||{});const truck=await prisma.truckAvailability.findUnique({where:{id:req.params.truckId}});if(!truck)return res.status(404).json({error:'Truck not found'});if(!PLATFORM.has(req.user.role)&&truck.carrierId!==carrierScope(req.user))return res.status(403).json({error:'Truck ownership required'});const loads=await prisma.marketplaceLoad.findMany({where:{status:{in:['POSTED','BIDDING']}},take:250});const options=Object.fromEntries(loads.map(load=>[load.id,{deadheadKm:input.deadheadByLoad[load.id],costs:input.costs}]));const ranking=rankLoadsForTruck(truck,loads,options);const recommendation={confidence:ranking[0]?.confidence||0,ranking,requiresHumanApproval:true,dataLabel:DATA_SOURCES.network};const audit=await record(req,{feature:'TRUCK_TO_LOAD_MATCH',entityType:'TRUCK_AVAILABILITY',entityId:truck.id,input,recommendation});return res.json({...recommendation,recommendationId:audit.id});}catch(error){next(error);}});

router.post('/deadhead',async(req,res,next)=>{try{if(!assertRole(req,res))return;const input=z.object({deadheadKm:z.number().nonnegative(),loadedKm:z.number().nonnegative(),costs:costsSchema}).parse(req.body);return res.json({...calculateDeadhead({deadheadKm:input.deadheadKm,loadedKm:input.loadedKm,...input.costs}),dataLabel:DATA_SOURCES.network});}catch(error){next(error);}});
router.get('/backhaul/:loadId',async(req,res,next)=>{try{if(!assertRole(req,res))return;const load=await prisma.marketplaceLoad.findUnique({where:{id:req.params.loadId}});if(!load)return res.status(404).json({error:'Load not found'});const candidates=await prisma.marketplaceLoad.findMany({where:{status:{in:['POSTED','BIDDING']}},take:250});return res.json({outbound:load,opportunities:findBackhaulOpportunities(load,candidates),dataLabel:DATA_SOURCES.network});}catch(error){next(error);}});
router.post('/multi-leg',async(req,res,next)=>{try{if(!assertRole(req,res))return;const input=z.object({loadIds:z.array(z.string()).min(2).max(8),costPerKm:z.number().nonnegative().default(0),maxDrivingHours:z.number().positive().max(24).default(13),averageSpeedKph:z.number().positive().max(140).default(80)}).parse(req.body);const loads=await prisma.marketplaceLoad.findMany({where:{id:{in:input.loadIds}}});const ordered=input.loadIds.map(id=>loads.find(load=>load.id===id)).filter(Boolean);return res.json({...planMultiLegTrip(ordered,input),dataLabel:DATA_SOURCES.network});}catch(error){next(error);}});

router.get('/rates',async(req,res,next)=>{try{if(!assertRole(req,res))return;const q=z.object({origin:z.string().min(2),destination:z.string().min(2),equipment:z.string().optional(),distanceKm:z.coerce.number().positive().optional()}).parse(req.query);const loads=await networkRows(q);return res.json({...buildRateIntelligence(observations(loads),{distanceKm:q.distanceKm}),query:q,dataNotice:'Loadlyx first-party network observations only. No DAT data is used.'});}catch(error){next(error);}});
router.post('/negotiation',async(req,res,next)=>{try{if(!assertRole(req,res))return;const input=z.object({origin:z.string().min(2),destination:z.string().min(2),equipment:z.string().optional(),distanceKm:z.number().positive(),askingCents:z.number().int().positive(),deadheadKm:z.number().nonnegative().default(0),costs:costsSchema}).parse(req.body);const loads=await networkRows(input);const rates=buildRateIntelligence(observations(loads),{distanceKm:input.distanceKm});const economics=calculateDeadhead({deadheadKm:input.deadheadKm,loadedKm:input.distanceKm,...input.costs});const recommendation=negotiationRecommendation({askingCents:input.askingCents,rateIntelligence:rates,economics});const audit=await record(req,{feature:'NEGOTIATION_ASSISTANT',entityType:'LANE',entityId:null,input,recommendation});return res.json({...recommendation,economics,rates,recommendationId:audit.id});}catch(error){next(error);}});
router.post('/recommendations/:id/action',async(req,res,next)=>{try{const input=z.object({action:z.enum(['ACCEPTED','REJECTED','DISMISSED']),outcome:z.record(z.any()).optional()}).parse(req.body);const row=await prisma.freightIntelligenceRecommendation.findUnique({where:{id:req.params.id}});if(!row||(!PLATFORM.has(req.user.role)&&row.userId!==req.user.userId&&row.tenantId!==req.user.tenantId))return res.status(403).json({error:'Recommendation access required'});return res.json(await prisma.freightIntelligenceRecommendation.update({where:{id:row.id},data:{userAction:input.action,outcome:input.outcome,actionedById:req.user.userId,actionedAt:new Date()}}));}catch(error){next(error);}});

router.get('/network',async(req,res,next)=>{try{if(!assertRole(req,res))return;const q=z.object({days:z.coerce.number().int().min(1).max(365).default(30),equipment:z.string().optional(),region:z.string().optional()}).parse(req.query);const since=new Date(Date.now()-q.days*86400000);const [loads,trucks]=await Promise.all([prisma.marketplaceLoad.findMany({where:{createdAt:{gte:since},...(q.equipment?{equipmentType:{equals:q.equipment,mode:'insensitive'}}:{}),...(q.region?{OR:[{originRegion:q.region},{destinationRegion:q.region}]}:{})},include:{bids:{where:{status:'ACCEPTED'}}},take:1000}),prisma.truckAvailability.findMany({where:{createdAt:{gte:since},...(q.equipment?{equipmentType:{equals:q.equipment,mode:'insensitive'}}:{}),...(q.region?{currentRegion:q.region}:{})},take:1000})]);const laneMap=new Map();for(const load of loads){const key=`${load.originCity} → ${load.destinationCity}`;const current=laneMap.get(key)||{lane:key,loads:0,accepted:0,postedRates:[],acceptedRates:[]};current.loads++;if(load.budgetCents)current.postedRates.push(load.budgetCents);for(const bid of load.bids){current.accepted++;current.acceptedRates.push(bid.amountCents);}laneMap.set(key,current);}const lanes=[...laneMap.values()].map(row=>({...row,averagePostedRateCents:row.postedRates.length?Math.round(row.postedRates.reduce((a,b)=>a+b,0)/row.postedRates.length):null,averageAcceptedRateCents:row.acceptedRates.length?Math.round(row.acceptedRates.reduce((a,b)=>a+b,0)/row.acceptedRates.length):null,postedRates:undefined,acceptedRates:undefined})).sort((a,b)=>b.loads-a.loads);return res.json({filters:q,conditions:buildMarketConditions({loads,trucks,accepted:loads.flatMap(load=>load.bids)}),lanes,originDensity:Object.entries(loads.reduce((a,l)=>(a[l.originCity]=(a[l.originCity]||0)+1,a),{})).map(([location,count])=>({location,count})),destinationDensity:Object.entries(loads.reduce((a,l)=>(a[l.destinationCity]=(a[l.destinationCity]||0)+1,a),{})).map(([location,count])=>({location,count})),equipmentDemand:Object.entries(loads.reduce((a,l)=>(a[l.equipmentType||'Unspecified']=(a[l.equipmentType||'Unspecified']||0)+1,a),{})).map(([equipment,count])=>({equipment,count})),dataLabel:DATA_SOURCES.network,privacy:'Aggregated network view; no identifiable competitor data'});}catch(error){next(error);}});
router.post('/benchmark',async(req,res,next)=>{try{if(!assertRole(req,res))return;const input=z.object({subject:z.record(z.number().nullable()),cohort:z.array(z.record(z.number().nullable())),minimumCohort:z.number().int().min(5).default(5)}).parse(req.body);return res.json(buildBenchmark(input));}catch(error){next(error);}});

router.get('/broker/tms',async(req,res,next)=>{try{if(!['BROKER','TENANT_ADMIN','TENANT_STAFF',...PLATFORM].includes(req.user.role))return res.status(403).json({error:'Broker TMS access required'});const loadWhere=PLATFORM.has(req.user.role)?{}:{OR:[{brokerId:req.user.userId},{posterId:req.user.userId},...(req.user.tenantId?[{poster:{tenantId:req.user.tenantId}}]:[])]};const [loads,quotes]=await Promise.all([prisma.marketplaceLoad.findMany({where:loadWhere,include:{bids:true,assignment:true,freightDocuments:true},orderBy:{updatedAt:'desc'},take:250}),req.user.tenantId?prisma.quote.findMany({where:{tenantId:req.user.tenantId},orderBy:{createdAt:'desc'},take:100}):[]]);const stages=['LEAD','QUOTE','ACCEPTED','CARRIER_SOURCING','OFFER','CARRIER_SELECTED','DISPATCH','TRACKING','POD','CUSTOMER_BILLING','CARRIER_SETTLEMENT','CLOSED'];const mapped=loads.map(load=>{const stage=load.status==='COMPLETED'?'CLOSED':load.status==='DELIVERED'?(load.freightDocuments.some(doc=>doc.category==='PROOF_OF_DELIVERY')?'CUSTOMER_BILLING':'POD'):load.assignment?(load.status==='IN_TRANSIT'?'TRACKING':'DISPATCH'):load.carrierId?'CARRIER_SELECTED':load.bids.length?'OFFER':'CARRIER_SOURCING';const suggestions=[];if(!load.carrierId&&load.bids.length)suggestions.push({type:'BEST_CARRIER',message:'Review ranked carrier options before award',approvalRequired:true});if(load.assignment&&!load.freightDocuments.some(doc=>doc.category==='RATE_CONFIRMATION'))suggestions.push({type:'MISSING_DOCUMENT',message:'Rate confirmation is missing',approvalRequired:true});if(load.status==='DELIVERED'&&!load.freightDocuments.some(doc=>doc.category==='PROOF_OF_DELIVERY'))suggestions.push({type:'MISSING_POD',message:'Proof of delivery is required before settlement',approvalRequired:true});return{...load,tmsStage:stage,suggestions};});return res.json({stages,quotes,loads:mapped,model:INTELLIGENCE_MODEL,notice:'AI recommendations are advisory and never change binding records without user approval'});}catch(error){next(error);}});

export default router;
