import crypto from 'crypto';
import { Router } from 'express';
import { z } from 'zod';
import { prisma } from '../db/prisma.js';
import { requireAuth } from '../middleware/requireauth.js';
import { assertAssignmentTransition, calculateRatePerMile, canPostTruck, canSearchTrucks, publicTrackingPoint, trackingIsAllowed } from '../services/loadlyxOneWorkflow.js';
import { calculateMarketplaceSplit, feeRuleSnapshot, payoutIsEligible, resolveMarketplaceFee } from '../services/marketplaceFinance.js';

const router = Router();
router.use(requireAuth);
const PLATFORM = new Set(['SUPER_ADMIN', 'PLATFORM_ADMIN', 'ADMIN', 'SUPPORT']);
const truckSchema = z.object({ truckId: z.string().min(1).max(120), equipmentType: z.string().min(2).max(120), trailerType: z.string().max(120).optional(), capacityKg: z.number().positive().optional(), currentCity: z.string().min(2).max(120), currentRegion: z.string().max(120).optional(), currentLatitude: z.number().min(-90).max(90).optional(), currentLongitude: z.number().min(-180).max(180).optional(), availableAt: z.coerce.date(), desiredDestination: z.string().max(240).optional(), maximumDeadheadKm: z.number().positive().optional(), operatingRadiusKm: z.number().positive().optional(), preferredLanesJson: z.array(z.record(z.any())).max(100).optional(), homeTerminal: z.string().max(240).optional(), teamDriver: z.boolean().default(false), recurringLaneRule: z.record(z.any()).optional(), specialCapabilities: z.array(z.string().max(120)).max(50).optional(), assignedDriverId: z.string().optional() });
const documentSchema = z.object({ category: z.enum(['BILL_OF_LADING','PROOF_OF_DELIVERY','RATE_CONFIRMATION','INVOICE','PHOTO','DAMAGE','INSURANCE','AUTHORITY','OTHER']), storageKey: z.string().min(4).max(500), privateUrl: z.string().url(), fileName: z.string().min(1).max(255), mimeType: z.enum(['application/pdf','image/jpeg','image/png','image/webp']), sizeBytes: z.number().int().positive().max(20 * 1024 * 1024), checksum: z.string().max(128).optional() });

function carrierScope(user) { return user.tenantId || user.userId; }
function participant(user, load) { return PLATFORM.has(user.role) || [load.posterId, load.brokerId, load.carrierId, load.assignment?.driverId].filter(Boolean).includes(user.userId); }

router.get('/workspace', async (req, res, next) => {
  try {
    const role = req.user.role;
    const loadWhere = role === 'DRIVER' ? { assignment: { driverId: req.user.userId } } : role === 'CARRIER' ? { OR: [{ carrierId: req.user.userId }, { bids: { some: { bidderId: req.user.userId } } }] } : role === 'BROKER' ? { OR: [{ brokerId: req.user.userId }, { posterId: req.user.userId }, { bids: { some: { bidderId: req.user.userId } } }] } : { posterId: req.user.userId };
    const [loads, trucks, savedSearches] = await Promise.all([
      prisma.marketplaceLoad.findMany({ where: loadWhere, include: { assignment: true, bids: { where: { OR: [{ bidderId: req.user.userId }, ...(role === 'BROKER' ? [{}] : [])] } } }, orderBy: { updatedAt: 'desc' }, take: 100 }),
      canPostTruck(role) ? prisma.truckAvailability.findMany({ where: { carrierId: carrierScope(req.user) }, orderBy: { availableAt: 'asc' }, take: 100 }) : [],
      prisma.freightSavedSearch.findMany({ where: { userId: req.user.userId }, orderBy: { updatedAt: 'desc' } })
    ]);
    return res.json({ role, loads, trucks, savedSearches });
  } catch (error) { return next(error); }
});

router.get('/loads/search', async (req, res, next) => {
  try {
    const q = req.query;
    const loads = await prisma.marketplaceLoad.findMany({ where: { status: { in: ['POSTED','BIDDING'] }, ...(q.origin ? { originCity: { contains: String(q.origin), mode: 'insensitive' } } : {}), ...(q.destination ? { destinationCity: { contains: String(q.destination), mode: 'insensitive' } } : {}), ...(q.equipment ? { equipmentType: { contains: String(q.equipment), mode: 'insensitive' } } : {}), ...(q.trailer ? { trailerType: { contains: String(q.trailer), mode: 'insensitive' } } : {}), ...(q.fullOrPartial ? { fullOrPartial: String(q.fullOrPartial).toUpperCase() } : {}), ...(q.hazmat === 'true' ? { hazmat: true } : {}), ...(q.teamDriver === 'true' ? { teamDriverRequired: true } : {}), ...(q.pickupFrom ? { pickupDate: { gte: new Date(String(q.pickupFrom)) } } : {}) }, include: { poster: { select: { id: true, fullName: true, role: true } }, bids: true }, take: 250 });
    const result = loads.map((load) => ({ ...load, ratePerMileCents: req.user ? calculateRatePerMile(load.budgetCents, load.distanceKm) : null, budgetCents: req.user ? load.budgetCents : null, bids: req.user ? load.bids : [] }));
    const sort = String(q.sort || 'newest');
    result.sort((a,b) => sort === 'highest_rate_per_mile' ? (b.ratePerMileCents || 0) - (a.ratePerMileCents || 0) : sort === 'highest_rate' ? (b.budgetCents || 0) - (a.budgetCents || 0) : new Date(b.createdAt) - new Date(a.createdAt));
    return res.json(result);
  } catch (error) { return next(error); }
});

router.post('/saved-searches', async (req, res, next) => { try { const input = z.object({ name: z.string().min(2).max(120), searchType: z.enum(['LOAD','TRUCK']), filtersJson: z.record(z.any()), alertsEnabled: z.boolean().default(false) }).parse(req.body); return res.status(201).json(await prisma.freightSavedSearch.upsert({ where: { userId_name_searchType: { userId: req.user.userId, name: input.name, searchType: input.searchType } }, update: input, create: { ...input, userId: req.user.userId } })); } catch (error) { return next(error); } });

router.get('/trucks', async (req, res, next) => {
  try { if (!canSearchTrucks(req.user.role)) return res.status(403).json({ error: 'Broker or authorized operating account required' }); const rows = await prisma.truckAvailability.findMany({ where: { status: 'AVAILABLE', ...(req.query.origin ? { currentCity: { contains: String(req.query.origin), mode: 'insensitive' } } : {}), ...(req.query.equipment ? { equipmentType: { contains: String(req.query.equipment), mode: 'insensitive' } } : {}) }, include: { assignedDriver: { select: { fullName: true } } }, orderBy: { availableAt: 'asc' }, take: 200 }); return res.json(rows.map(({ currentLatitude, currentLongitude, ...row }) => ({ ...row, approximateLocation: row.currentCity, coordinatesAvailableToAuthorizedAssignment: Boolean(currentLatitude && currentLongitude) }))); } catch (error) { return next(error); }
});
router.post('/trucks', async (req, res, next) => { try { if (!canPostTruck(req.user.role)) return res.status(403).json({ error: 'Carrier or authorized driver/dispatcher required' }); const input = truckSchema.parse(req.body); return res.status(201).json(await prisma.truckAvailability.create({ data: { ...input, carrierId: carrierScope(req.user), createdById: req.user.userId, capacityKg: input.capacityKg ? String(input.capacityKg) : null, currentLatitude: input.currentLatitude ? String(input.currentLatitude) : null, currentLongitude: input.currentLongitude ? String(input.currentLongitude) : null, maximumDeadheadKm: input.maximumDeadheadKm ? String(input.maximumDeadheadKm) : null, operatingRadiusKm: input.operatingRadiusKm ? String(input.operatingRadiusKm) : null } })); } catch (error) { return next(error); } });
router.put('/trucks/:id', async (req, res, next) => { try { const row = await prisma.truckAvailability.findUnique({ where: { id: req.params.id } }); if (!row || (row.carrierId !== carrierScope(req.user) && !PLATFORM.has(req.user.role))) return res.status(403).json({ error: 'Forbidden' }); const input = truckSchema.partial().parse(req.body); return res.json(await prisma.truckAvailability.update({ where: { id: row.id }, data: input })); } catch (error) { return next(error); } });
router.delete('/trucks/:id', async (req, res, next) => { try { const row = await prisma.truckAvailability.findUnique({ where: { id: req.params.id } }); if (!row || (row.carrierId !== carrierScope(req.user) && !PLATFORM.has(req.user.role))) return res.status(403).json({ error: 'Forbidden' }); return res.json(await prisma.truckAvailability.update({ where: { id: row.id }, data: { status: 'UNAVAILABLE' } })); } catch (error) { return next(error); } });
router.post('/trucks/:id/clone', async (req, res, next) => { try { const row = await prisma.truckAvailability.findUnique({ where: { id: req.params.id } }); if (!row || row.carrierId !== carrierScope(req.user)) return res.status(403).json({ error: 'Forbidden' }); const { id, createdAt, updatedAt, ...copy } = row; return res.status(201).json(await prisma.truckAvailability.create({ data: { ...copy, status: 'AVAILABLE', availableAt: req.body?.availableAt ? new Date(req.body.availableAt) : new Date() } })); } catch (error) { return next(error); } });

router.post('/loads/:id/instant-book', async (req, res, next) => {
  try {
    if (!['CARRIER','BROKER','TENANT_ADMIN'].includes(req.user.role)) return res.status(403).json({ error: 'Eligible provider required' });
    const idempotencyKey = z.string().min(8).max(200).parse(req.headers['idempotency-key'] || req.body?.idempotencyKey);
    const existing = await prisma.marketplaceTransaction.findUnique({ where: { idempotencyKey } }); if (existing) return res.json(existing);
    const profile = await prisma.providerPayoutProfile.findUnique({ where: { userId: req.user.userId } }); if (!payoutIsEligible(profile)) return res.status(409).json({ error: 'Provider verification and payouts must be enabled' });
    const result = await prisma.$transaction(async (tx) => {
      const load = await tx.marketplaceLoad.findUnique({ where: { id: req.params.id } });
      if (!load?.instantBookEnabled || !load.instantBookCents || !['POSTED','BIDDING'].includes(load.status)) throw new Error('Load is not available for instant booking');
      const locked = await tx.marketplaceLoad.updateMany({ where: { id: load.id, status: { in: ['POSTED','BIDDING'] }, carrierId: null }, data: { status: 'AWARDED', carrierId: req.user.userId, awardedAmountCents: load.instantBookCents } });
      if (locked.count !== 1) throw new Error('Load was already booked');
      const offer = await tx.marketplaceBid.upsert({ where: { loadId_bidderId: { loadId: load.id, bidderId: req.user.userId } }, update: { amountCents: load.instantBookCents, status: 'ACCEPTED', acceptedAt: new Date() }, create: { loadId: load.id, bidderId: req.user.userId, amountCents: load.instantBookCents, currency: load.currency, status: 'ACCEPTED', acceptedAt: new Date() } });
      await tx.marketplaceBid.updateMany({ where: { loadId: load.id, id: { not: offer.id } }, data: { status: 'REJECTED' } });
      const rule = await resolveMarketplaceFee({ accountType: req.user.role, currency: load.currency, client: tx }); const split = calculateMarketplaceSplit(load.instantBookCents, rule);
      return tx.marketplaceTransaction.create({ data: { idempotencyKey, loadId: load.id, offerId: offer.id, posterId: load.posterId, providerId: req.user.userId, providerType: req.user.role, currency: load.currency, ...split, feeRuleSnapshotJson: feeRuleSnapshot(rule), agreementSnapshotJson: { mode: 'INSTANT_BOOK', acceptedAt: new Date().toISOString(), rules: load.instantBookRules } } });
    }, { isolationLevel: 'Serializable' });
    return res.status(201).json(result);
  } catch (error) { return next(error); }
});

router.post('/loads/:id/assignment', async (req, res, next) => { try { const input = z.object({ driverId: z.string(), truckId: z.string().optional() }).parse(req.body); const load = await prisma.marketplaceLoad.findUnique({ where: { id: req.params.id } }); if (!load || !(PLATFORM.has(req.user.role) || load.carrierId === req.user.userId)) return res.status(403).json({ error: 'Winning carrier required' }); const driver = await prisma.user.findFirst({ where: { id: input.driverId, role: 'DRIVER', isActive: true } }); if (!driver) return res.status(404).json({ error: 'Active driver not found' }); return res.status(201).json(await prisma.freightAssignment.upsert({ where: { loadId: load.id }, update: { ...input, carrierId: load.carrierId, assignedById: req.user.userId, status: 'ASSIGNMENT_PENDING' }, create: { loadId: load.id, ...input, carrierId: load.carrierId, assignedById: req.user.userId } })); } catch (error) { return next(error); } });
router.put('/assignments/:id/status', async (req, res, next) => { try { const input = z.object({ status: z.enum(['DRIVER_ACCEPTED','DRIVER_DECLINED','EN_ROUTE_PICKUP','ARRIVED_PICKUP','LOADED','IN_TRANSIT','ARRIVED_DELIVERY','DELIVERED','POD_PENDING','COMPLETE']), note: z.string().max(1000).optional() }).parse(req.body); const assignment = await prisma.freightAssignment.findUnique({ where: { id: req.params.id } }); if (!assignment || !(PLATFORM.has(req.user.role) || assignment.driverId === req.user.userId || assignment.carrierId === carrierScope(req.user))) return res.status(403).json({ error: 'Assignment access required' }); assertAssignmentTransition(assignment.status, input.status); const updated = await prisma.$transaction(async (tx) => { const row = await tx.freightAssignment.update({ where: { id: assignment.id }, data: { status: input.status, ...(input.status === 'DRIVER_ACCEPTED' ? { acceptedAt: new Date() } : {}), ...(input.status === 'COMPLETE' ? { completedAt: new Date() } : {}) } }); await tx.freightStatusEvent.create({ data: { assignmentId: row.id, actorUserId: req.user.userId, fromStatus: assignment.status, toStatus: input.status, note: input.note } }); return row; }); return res.json(updated); } catch (error) { return next(error); } });

router.put('/driver/tracking-consent', async (req, res, next) => { try { if (req.user.role !== 'DRIVER') return res.status(403).json({ error: 'Driver account required' }); const consent = z.boolean().parse(req.body?.consent); return res.json(await prisma.freightDriverProfile.upsert({ where: { userId: req.user.userId }, update: consent ? { trackingConsentAt: new Date(), trackingRevokedAt: null } : { trackingRevokedAt: new Date() }, create: { userId: req.user.userId, ...(consent ? { trackingConsentAt: new Date() } : { trackingRevokedAt: new Date() }) } })); } catch (error) { return next(error); } });
router.post('/loads/:id/tracking', async (req, res, next) => { try { const input = z.object({ latitude: z.number().min(-90).max(90), longitude: z.number().min(-180).max(180), accuracyMeters: z.number().int().positive().optional(), speedKph: z.number().nonnegative().max(250).optional(), headingDegrees: z.number().int().min(0).max(359).optional(), eta: z.coerce.date().optional() }).parse(req.body); const [assignment, profile] = await Promise.all([prisma.freightAssignment.findUnique({ where: { loadId: req.params.id } }), prisma.freightDriverProfile.findUnique({ where: { userId: req.user.userId } })]); if (!trackingIsAllowed({ assignment, driverId: req.user.userId, profile })) return res.status(403).json({ error: 'Active assignment and tracking consent required' }); return res.status(201).json(await prisma.freightTrackingPoint.create({ data: { loadId: req.params.id, driverId: req.user.userId, latitude: String(input.latitude), longitude: String(input.longitude), accuracyMeters: input.accuracyMeters, speedKph: input.speedKph ? String(input.speedKph) : null, headingDegrees: input.headingDegrees, eta: input.eta, retentionExpires: new Date(Date.now() + 30 * 86400000) } })); } catch (error) { return next(error); } });
router.get('/loads/:id/tracking', async (req, res, next) => { try { const load = await prisma.marketplaceLoad.findUnique({ where: { id: req.params.id }, include: { assignment: true } }); if (!load || !participant(req.user, load)) return res.status(403).json({ error: 'Load participant access required' }); const point = await prisma.freightTrackingPoint.findFirst({ where: { loadId: load.id }, orderBy: { capturedAt: 'desc' } }); return res.json({ loadId: load.id, status: load.assignment?.status || load.status, current: publicTrackingPoint(point), lastUpdate: point?.capturedAt || null }); } catch (error) { return next(error); } });
router.post('/loads/:id/geofences', async (req, res, next) => { try { const type = z.enum(['APPROACHING_PICKUP','ARRIVED_PICKUP','DEPARTED_PICKUP','APPROACHING_DELIVERY','ARRIVED_DELIVERY']).parse(req.body?.type); const load = await prisma.marketplaceLoad.findUnique({ where: { id: req.params.id }, include: { assignment: true } }); if (!load || load.assignment?.driverId !== req.user.userId) return res.status(403).json({ error: 'Assigned driver required' }); return res.status(201).json(await prisma.freightGeofenceEvent.create({ data: { loadId: load.id, type, metadataJson: { suggestedOnly: true } } })); } catch (error) { return next(error); } });

router.get('/loads/:id/documents', async (req, res, next) => { try { const load = await prisma.marketplaceLoad.findUnique({ where: { id: req.params.id }, include: { assignment: true } }); if (!load || !participant(req.user, load)) return res.status(403).json({ error: 'Load participant access required' }); return res.json(await prisma.freightDocument.findMany({ where: { loadId: load.id }, orderBy: { createdAt: 'desc' } })); } catch (error) { return next(error); } });
router.post('/loads/:id/documents', async (req, res, next) => { try { const input = documentSchema.parse(req.body); const load = await prisma.marketplaceLoad.findUnique({ where: { id: req.params.id }, include: { assignment: true } }); if (!load || !participant(req.user, load)) return res.status(403).json({ error: 'Load participant access required' }); const row = await prisma.freightDocument.create({ data: { ...input, loadId: load.id, uploadedById: req.user.userId } }); await prisma.auditEvent.create({ data: { actorUserId: req.user.userId, action: 'FREIGHT_DOCUMENT_UPLOADED', entityType: 'FREIGHT_DOCUMENT', entityId: row.id, afterJson: { loadId: load.id, category: row.category, checksum: row.checksum } } }); return res.status(201).json(row); } catch (error) { return next(error); } });

export default router;
