import crypto from 'crypto';
import { Router } from 'express';
import { z } from 'zod';
import { prisma } from '../db/prisma.js';
import { requireAuth, requirePlatformRole } from '../middleware/requireauth.js';
import { createAiProvider, requestHash, sanitizeAiInput } from '../services/aiService.js';
import { assertApprovalTransition, evaluateApprovalPolicy } from '../services/approvalPolicy.js';
import { enqueueJob } from '../services/durableQueue.js';
import { PLATFORM_EVENTS, publishEvent } from '../services/eventBus.js';
import { applyInventoryMovement, availableStock } from '../services/inventoryService.js';
import { assertToteTransition } from '../services/toteService.js';
import { environmentVariableAudit, providerConfigurationStatus } from '../services/providerStatus.js';

const router = Router();
router.use(requireAuth);
const PLATFORM_ROLES = new Set(['SUPER_ADMIN','PLATFORM_ADMIN','ADMIN','SUPPORT']);
const WRITE_ROLES = new Set(['SUPER_ADMIN','PLATFORM_ADMIN','ADMIN','TENANT_ADMIN']);

function tenantScope(req, requested = null, required = true) {
  const tenantId = PLATFORM_ROLES.has(req.user.role) ? requested : req.user.tenantId;
  if (required && !tenantId) { const error = new Error('Tenant context is required'); error.status = 400; throw error; }
  if (!PLATFORM_ROLES.has(req.user.role) && requested && requested !== req.user.tenantId) { const error = new Error('Cross-tenant access denied'); error.status = 403; throw error; }
  return tenantId || null;
}
function requireWrite(req, res, next) { return WRITE_ROLES.has(req.user.role) ? next() : res.status(403).json({ error: 'Write access denied' }); }
async function audit(req, action, entityType, entityId, tenantId, afterJson, reason = null) {
  await prisma.auditEvent.create({ data: { actorUserId: req.user.userId, action, entityType, entityId, tenantId, afterJson, reason } });
}

router.get('/catalog/events', (_req, res) => res.json({ events: PLATFORM_EVENTS }));
router.post('/events', requireWrite, async (req, res, next) => {
  try {
    const input = z.object({ tenantId: z.string().optional(), eventType: z.enum(PLATFORM_EVENTS), aggregateType: z.string().min(1).max(80), aggregateId: z.string().min(1).max(200), payload: z.record(z.any()).default({}), metadata: z.record(z.any()).default({}), idempotencyKey: z.string().min(8).max(200), correlationId: z.string().max(200).optional() }).parse(req.body);
    const tenantId = tenantScope(req, input.tenantId, false);
    return res.status(201).json(await publishEvent({ ...input, tenantId }));
  } catch (error) { return next(error); }
});

router.get('/workflows', async (req, res, next) => { try { const tenantId = tenantScope(req, req.query.tenantId || null, false); return res.json(await prisma.workflowDefinition.findMany({ where: PLATFORM_ROLES.has(req.user.role) && !tenantId ? {} : { OR: [{ tenantId }, { tenantId: null }] }, orderBy: [{ key: 'asc' }, { version: 'desc' }] })); } catch (error) { return next(error); } });
router.post('/workflows', requireWrite, async (req, res, next) => {
  try {
    const input = z.object({ tenantId: z.string().optional(), key: z.string().regex(/^[a-z0-9.-]+$/), name: z.string().min(2).max(120), version: z.number().int().positive().default(1), triggerType: z.enum(PLATFORM_EVENTS), definition: z.object({ steps: z.array(z.object({ type: z.enum(['ACTION','CONDITION','DELAY','APPROVAL']), action: z.string().max(100).optional(), config: z.record(z.any()).default({}) })).min(1).max(50) }), enabled: z.boolean().default(false) }).parse(req.body);
    const tenantId = tenantScope(req, input.tenantId, false);
    const row = await prisma.workflowDefinition.create({ data: { ...input, tenantId, scopeKey: tenantId ? `TENANT:${tenantId}` : 'GLOBAL' } });
    await audit(req, 'WORKFLOW_CREATED', 'WORKFLOW', row.id, tenantId, row);
    return res.status(201).json(row);
  } catch (error) { return next(error); }
});
router.put('/workflows/:id/status', requireWrite, async (req, res, next) => { try { const enabled = z.boolean().parse(req.body?.enabled); const row = await prisma.workflowDefinition.findUnique({ where: { id: req.params.id } }); if (!row) return res.status(404).json({ error: 'Workflow not found' }); tenantScope(req, row.tenantId, false); const saved = await prisma.workflowDefinition.update({ where: { id: row.id }, data: { enabled } }); await audit(req, 'WORKFLOW_STATUS_CHANGED', 'WORKFLOW', row.id, row.tenantId, saved, req.body?.reason || null); return res.json(saved); } catch (error) { return next(error); } });
router.get('/workflow-runs', async (req, res, next) => { try { const tenantId = tenantScope(req, req.query.tenantId || null, false); return res.json(await prisma.workflowRun.findMany({ where: tenantId ? { tenantId } : {}, include: { workflow: { select: { key: true, name: true, version: true } }, event: { select: { eventType: true, aggregateType: true, aggregateId: true } } }, orderBy: { createdAt: 'desc' }, take: 250 })); } catch (error) { return next(error); } });

router.get('/jobs/health', requirePlatformRole, async (_req, res, next) => { try { const grouped = await prisma.backgroundJob.groupBy({ by: ['status','queueName'], _count: true }); const oldestQueued = await prisma.backgroundJob.findFirst({ where: { status: { in: ['QUEUED','RETRY_SCHEDULED'] } }, orderBy: { availableAt: 'asc' }, select: { availableAt: true } }); return res.json({ grouped, oldestQueuedAt: oldestQueued?.availableAt || null, checkedAt: new Date().toISOString() }); } catch (error) { return next(error); } });
router.post('/jobs', requireWrite, async (req, res, next) => { try { const input = z.object({ tenantId: z.string().optional(), jobType: z.string().min(2).max(100), queueName: z.string().max(60).default('default'), payload: z.record(z.any()), idempotencyKey: z.string().min(8).max(200), availableAt: z.coerce.date().optional() }).parse(req.body); const tenantId = tenantScope(req, input.tenantId, false); return res.status(201).json(await enqueueJob({ ...input, tenantId })); } catch (error) { return next(error); } });

router.get('/ai/agents', async (req, res, next) => { try { const tenantId = tenantScope(req, req.query.tenantId || null, false); return res.json(await prisma.aiAgentDefinition.findMany({ where: { OR: [{ tenantId }, { tenantId: null }], enabled: true }, orderBy: [{ key: 'asc' }, { version: 'desc' }] })); } catch (error) { return next(error); } });
router.post('/ai/agents', requireWrite, async (req, res, next) => { try { const input = z.object({ tenantId: z.string().optional(), key: z.string().regex(/^[a-z0-9.-]+$/), name: z.string().min(2).max(120), version: z.number().int().positive().default(1), module: z.string().min(2).max(40), outputSchemaVersion: z.string().max(30).default('1'), instructions: z.string().min(20).max(20000), enabled: z.boolean().default(false), minConfidence: z.number().min(0).max(1).default(0.8), allowedRoles: z.array(z.string()).min(1), policy: z.record(z.any()).optional() }).parse(req.body); const tenantId = tenantScope(req, input.tenantId, false); const row = await prisma.aiAgentDefinition.create({ data: { ...input, tenantId, scopeKey: tenantId ? `TENANT:${tenantId}` : 'GLOBAL', policyJson: input.policy, minConfidence: input.minConfidence } }); await audit(req, 'AI_AGENT_CREATED', 'AI_AGENT', row.id, tenantId, row); return res.status(201).json(row); } catch (error) { return next(error); } });
router.post('/ai/recommendations', async (req, res, next) => {
  try {
    const input = z.object({ agentKey: z.string(), input: z.string(), actionType: z.string().max(80), inputReferences: z.array(z.object({ type: z.string(), id: z.string() })).max(100).default([]), facts: z.record(z.any()).default({}) }).parse(req.body);
    const tenantId = tenantScope(req, null, false);
    const agent = await prisma.aiAgentDefinition.findFirst({ where: { key: input.agentKey, enabled: true, OR: [{ tenantId }, { tenantId: null }] }, orderBy: { version: 'desc' } });
    if (!agent) return res.status(404).json({ error: 'Enabled AI agent not found' });
    if (!(agent.allowedRoles || []).includes(req.user.role)) return res.status(403).json({ error: 'Role is not permitted to use this agent' });
    const provider = createAiProvider();
    const clean = sanitizeAiInput(input.input);
    const generated = await provider.generate({ module: agent.module, instructions: `${agent.instructions}\nReturn valid JSON only.`, input: clean });
    let output; try { output = JSON.parse(generated.text); } catch { output = { summary: generated.text }; }
    const confidence = Number(output.confidenceScore ?? 0.5);
    const riskLevel = ['LOW','MEDIUM','HIGH','CRITICAL'].includes(output.riskLevel) ? output.riskLevel : 'MEDIUM';
    const decision = evaluateApprovalPolicy({ actionType: input.actionType, confidenceScore: confidence, riskLevel, policy: agent.policyJson || {}, facts: input.facts });
    const recommendation = await prisma.$transaction(async (tx) => {
      const row = await tx.aiRecommendation.create({ data: { tenantId, userId: req.user.userId, agentKey: agent.key, agentVersion: agent.version, recommendationVersion: `${agent.key}:${agent.version}`, outputSchemaVersion: agent.outputSchemaVersion, confidenceScore: decision.confidenceScore, riskLevel, manualReviewRequired: decision.manualReviewRequired, manualReviewReasons: decision.manualReviewReasons, inputReferences: input.inputReferences, inputHash: requestHash({ tenantId, userId: req.user.userId, module: agent.module, input: clean }), outputJson: output, status: decision.manualReviewRequired ? 'PENDING_APPROVAL' : 'APPROVED', provider: provider.name, model: provider.model } });
      await tx.aiUsageEvent.create({ data: { tenantId, userId: req.user.userId, module: agent.module, provider: provider.name, model: provider.model, inputTokens: generated.inputTokens || 0, outputTokens: generated.outputTokens || 0, status: 'SUCCESS', requestHash: row.inputHash } });
      if (decision.manualReviewRequired) await tx.approvalRequest.create({ data: { tenantId, recommendationId: row.id, requestedById: req.user.userId, actionType: input.actionType, targetType: 'AI_RECOMMENDATION', targetId: row.id, riskLevel, requestedJson: output } });
      return row;
    });
    return res.status(201).json(recommendation);
  } catch (error) { return next(error); }
});
router.get('/ai/recommendations', async (req, res, next) => { try { const tenantId = tenantScope(req, req.query.tenantId || null, false); return res.json(await prisma.aiRecommendation.findMany({ where: tenantId ? { tenantId } : { userId: req.user.userId }, orderBy: { createdAt: 'desc' }, take: 250 })); } catch (error) { return next(error); } });

router.get('/approvals', async (req, res, next) => { try { const tenantId = tenantScope(req, req.query.tenantId || null, false); return res.json(await prisma.approvalRequest.findMany({ where: tenantId ? { tenantId } : { requestedById: req.user.userId }, include: { recommendation: true }, orderBy: { createdAt: 'desc' }, take: 250 })); } catch (error) { return next(error); } });
router.post('/approvals/:id/decision', requireWrite, async (req, res, next) => { try { const input = z.object({ decision: z.enum(['APPROVED','REJECTED']), reason: z.string().min(3).max(1000), editedOutput: z.record(z.any()).optional() }).parse(req.body); const before = await prisma.approvalRequest.findUnique({ where: { id: req.params.id } }); if (!before) return res.status(404).json({ error: 'Approval request not found' }); tenantScope(req, before.tenantId, false); assertApprovalTransition(before.status, input.decision); const saved = await prisma.$transaction(async (tx) => { const approval = await tx.approvalRequest.update({ where: { id: before.id }, data: { status: input.decision, reason: input.reason, decidedById: req.user.userId, decidedJson: input.editedOutput, decidedAt: new Date() } }); if (before.recommendationId) await tx.aiRecommendation.update({ where: { id: before.recommendationId }, data: { status: input.decision, ...(input.editedOutput ? { outputJson: input.editedOutput } : {}) } }); await tx.auditEvent.create({ data: { actorUserId: req.user.userId, action: `APPROVAL_${input.decision}`, entityType: 'APPROVAL', entityId: before.id, tenantId: before.tenantId, beforeJson: before, afterJson: approval, reason: input.reason } }); return approval; }); return res.json(saved); } catch (error) { return next(error); } });

router.get('/notifications', async (req, res, next) => { try { return res.json(await prisma.notification.findMany({ where: { userId: req.user.userId }, orderBy: { createdAt: 'desc' }, take: 200 })); } catch (error) { return next(error); } });
router.post('/notifications/:id/read', async (req, res, next) => { try { const row = await prisma.notification.findFirst({ where: { id: req.params.id, userId: req.user.userId } }); if (!row) return res.status(404).json({ error: 'Notification not found' }); return res.json(await prisma.notification.update({ where: { id: row.id }, data: { readAt: new Date() } })); } catch (error) { return next(error); } });

router.get('/inventory', async (req, res, next) => { try { const tenantId = tenantScope(req, req.query.tenantId || null); const rows = await prisma.inventoryStock.findMany({ where: { tenantId }, include: { product: { select: { name: true, sku: true } }, location: true }, orderBy: { updatedAt: 'desc' } }); return res.json(rows.map((row) => ({ ...row, available: availableStock(row) }))); } catch (error) { return next(error); } });
router.post('/inventory/locations', requireWrite, async (req, res, next) => { try { const input = z.object({ tenantId: z.string().optional(), name: z.string().min(2), code: z.string().regex(/^[A-Z0-9_-]+$/), address: z.record(z.any()).optional(), pickupEnabled: z.boolean().default(false), deliveryEnabled: z.boolean().default(false) }).parse(req.body); const tenantId = tenantScope(req, input.tenantId); return res.status(201).json(await prisma.inventoryLocation.create({ data: { tenantId, name: input.name, code: input.code, addressJson: input.address, pickupEnabled: input.pickupEnabled, deliveryEnabled: input.deliveryEnabled } })); } catch (error) { return next(error); } });
router.post('/inventory/movements', requireWrite, async (req, res, next) => { try { const input = z.object({ tenantId: z.string().optional(), productId: z.string(), locationId: z.string(), movementType: z.enum(['RECEIPT','RESERVATION','RELEASE','SALE','RETURN','TRANSFER_IN','TRANSFER_OUT','ADJUSTMENT','DAMAGE']), quantity: z.number().int().positive(), idempotencyKey: z.string().min(8), reason: z.string().max(500).optional(), referenceType: z.string().max(80).optional(), referenceId: z.string().max(200).optional() }).parse(req.body); const tenantId = tenantScope(req, input.tenantId); const saved = await prisma.$transaction(async (tx) => { const existing = await tx.inventoryMovement.findUnique({ where: { idempotencyKey: input.idempotencyKey } }); if (existing) return existing; const product = await tx.product.findFirst({ where: { id: input.productId, tenantId } }); const location = await tx.inventoryLocation.findFirst({ where: { id: input.locationId, tenantId } }); if (!product || !location) throw new Error('Tenant-owned product and location are required'); const stock = await tx.inventoryStock.upsert({ where: { productId_locationId: { productId: product.id, locationId: location.id } }, update: {}, create: { tenantId, productId: product.id, locationId: location.id } }); const nextStock = applyInventoryMovement(stock, input.movementType, input.quantity); await tx.inventoryStock.update({ where: { id: stock.id }, data: { onHand: nextStock.onHand, reserved: nextStock.reserved } }); return tx.inventoryMovement.create({ data: { tenantId, productId: product.id, locationId: location.id, movementType: input.movementType, quantity: input.quantity, idempotencyKey: input.idempotencyKey, reason: input.reason, referenceType: input.referenceType, referenceId: input.referenceId, actorUserId: req.user.userId } }); }); return res.status(201).json(saved); } catch (error) { return next(error); } });

router.get('/totes', async (req, res, next) => { try { const tenantId = tenantScope(req, req.query.tenantId || null); return res.json(await prisma.toteAsset.findMany({ where: { tenantId }, orderBy: { identifier: 'asc' } })); } catch (error) { return next(error); } });
router.post('/totes', requireWrite, async (req, res, next) => { try { const input = z.object({ tenantId: z.string().optional(), identifier: z.string().min(2).max(80), inventoryLocation: z.string().max(200).optional() }).parse(req.body); const tenantId = tenantScope(req, input.tenantId); const rawToken = crypto.randomBytes(24).toString('base64url'); const row = await prisma.toteAsset.create({ data: { tenantId, identifier: input.identifier, inventoryLocation: input.inventoryLocation, qrTokenHash: crypto.createHash('sha256').update(rawToken).digest('hex') } }); return res.status(201).json({ ...row, qrToken: rawToken }); } catch (error) { return next(error); } });
router.post('/totes/:id/state', requireWrite, async (req, res, next) => { try { const input = z.object({ state: z.enum(['AVAILABLE','RESERVED','OUT_FOR_DELIVERY','RENTED','OVERDUE','RETURNED','CLEANING','DAMAGED','LOST','RETIRED']), reason: z.string().max(500).optional() }).parse(req.body); const tote = await prisma.toteAsset.findUnique({ where: { id: req.params.id } }); if (!tote) return res.status(404).json({ error: 'Tote not found' }); tenantScope(req, tote.tenantId); assertToteTransition(tote.state, input.state); const saved = await prisma.$transaction(async (tx) => { const row = await tx.toteAsset.update({ where: { id: tote.id }, data: { state: input.state, ...(input.state === 'AVAILABLE' && tote.state !== 'AVAILABLE' ? { reuseCount: { increment: 1 } } : {}) } }); await tx.toteLifecycleEvent.create({ data: { toteId: tote.id, actorUserId: req.user.userId, eventType: input.reason || 'STATE_CHANGED', fromState: tote.state, toState: input.state } }); return row; }); return res.json(saved); } catch (error) { return next(error); } });
router.post('/tote-rentals', requireWrite, async (req, res, next) => { try { const input = z.object({ tenantId: z.string().optional(), toteIds: z.array(z.string()).min(1).max(200), customerEmail: z.string().email(), customerUserId: z.string().optional(), orderId: z.string().optional(), dueDate: z.coerce.date(), deliveryDate: z.coerce.date().optional(), depositCents: z.number().int().min(0).default(0), replacementCents: z.number().int().min(0).default(0) }).parse(req.body); const tenantId = tenantScope(req, input.tenantId); const rental = await prisma.$transaction(async (tx) => { const totes = await tx.toteAsset.findMany({ where: { id: { in: input.toteIds }, tenantId } }); if (totes.length !== new Set(input.toteIds).size || totes.some((tote) => tote.state !== 'AVAILABLE')) throw new Error('Every tote must belong to the tenant and be available'); const row = await tx.toteRental.create({ data: { tenantId, customerEmail: input.customerEmail, customerUserId: input.customerUserId, orderId: input.orderId, dueDate: input.dueDate, deliveryDate: input.deliveryDate, depositCents: input.depositCents, replacementCents: input.replacementCents, items: { create: totes.map((tote) => ({ toteId: tote.id })) } }, include: { items: true } }); for (const tote of totes) { await tx.toteAsset.update({ where: { id: tote.id }, data: { state: 'RESERVED' } }); await tx.toteLifecycleEvent.create({ data: { toteId: tote.id, actorUserId: req.user.userId, eventType: 'RENTAL_RESERVED', fromState: 'AVAILABLE', toState: 'RESERVED', metadataJson: { rentalId: row.id } } }); } return row; }); return res.status(201).json(rental); } catch (error) { return next(error); } });
router.get('/tote-rentals', async (req, res, next) => { try { const tenantId = tenantScope(req, req.query.tenantId || null); return res.json(await prisma.toteRental.findMany({ where: { tenantId }, include: { items: { include: { tote: true } } }, orderBy: { createdAt: 'desc' }, take: 250 })); } catch (error) { return next(error); } });

router.post('/digital-passes', requireWrite, async (req, res, next) => { try { const input = z.object({ tenantId: z.string().optional(), userId: z.string().optional(), provider: z.enum(['INTERNAL','APPLE','GOOGLE']).default('INTERNAL'), passType: z.enum(['MOVE_BOOKING','ORDER_PICKUP','TOTE_RETURN','DELIVERY_STATUS','APPOINTMENT']), referenceType: z.string().max(80), referenceId: z.string().max(200), payload: z.record(z.any()), expiresAt: z.coerce.date().optional() }).parse(req.body); const tenantId = tenantScope(req, input.tenantId); if (input.provider !== 'INTERNAL') { const configured = input.provider === 'APPLE' ? process.env.APPLE_PASS_CERTIFICATE : process.env.GOOGLE_WALLET_CREDENTIALS; if (!configured) return res.status(503).json({ error: `${input.provider} Wallet is not configured`, externalVerificationRequired: true }); } const serialNumber = crypto.randomUUID(); const qrSecret = process.env.DIGITAL_PASS_SIGNING_SECRET || process.env.JWT_SECRET; if (!qrSecret) throw new Error('DIGITAL_PASS_SIGNING_SECRET or JWT_SECRET is required'); const qrToken = crypto.createHmac('sha256', qrSecret).update(`${tenantId}:${input.referenceType}:${input.referenceId}:${serialNumber}`).digest('base64url'); const row = await prisma.digitalPass.upsert({ where: { provider_referenceType_referenceId: { provider: input.provider, referenceType: input.referenceType, referenceId: input.referenceId } }, update: { payloadJson: { ...input.payload, qrToken }, expiresAt: input.expiresAt, status: 'ACTIVE' }, create: { tenantId, userId: input.userId, provider: input.provider, passType: input.passType, referenceType: input.referenceType, referenceId: input.referenceId, serialNumber, payloadJson: { ...input.payload, qrToken }, expiresAt: input.expiresAt } }); return res.status(201).json(row); } catch (error) { return next(error); } });
router.get('/digital-passes', async (req, res, next) => { try { const tenantId = tenantScope(req, req.query.tenantId || null); return res.json(await prisma.digitalPass.findMany({ where: PLATFORM_ROLES.has(req.user.role) ? { tenantId } : { tenantId, OR: [{ userId: req.user.userId }, { userId: null }] }, orderBy: { createdAt: 'desc' }, take: 200 })); } catch (error) { return next(error); } });

router.get('/metrics/outcomes', async (req, res, next) => { try { const tenantId = tenantScope(req, req.query.tenantId || null, false); const where = tenantId ? { tenantId } : {}; const [quotes, acceptedQuotes, orders, orderValue, loads, completedLoads] = await Promise.all([prisma.quote.count({ where }), prisma.quote.count({ where: { ...where, status: { in: ['CONVERTED','LOAD_CREATED'] } } }), prisma.order.count({ where }), prisma.order.aggregate({ where: { ...where, paymentStatus: 'PAID' }, _sum: { totalCents: true } }), prisma.load.count({ where }), prisma.load.count({ where: { ...where, status: 'COMPLETED' } })]); return res.json({ sources: { quoteCount: quotes, convertedQuoteCount: acceptedQuotes, paidOrderCount: orders, loadCount: loads, completedLoadCount: completedLoads }, metrics: { quoteConversionRate: quotes ? acceptedQuotes / quotes : null, paidStoreValueCents: orderValue._sum.totalCents || 0, loadCompletionRate: loads ? completedLoads / loads : null }, calculatedAt: new Date().toISOString() }); } catch (error) { return next(error); } });

router.get('/admin/integrations', requirePlatformRole, (_req, res) => res.json({ ...providerConfigurationStatus(), ai: { configured: Boolean(process.env.AI_API_KEY), provider: process.env.AI_PROVIDER || 'DISABLED' }, jobs: { provider: 'POSTGRES_DURABLE_QUEUE' }, sms: { configured: Boolean(process.env.SMS_PROVIDER_KEY) }, maps: { configured: Boolean(process.env.MAPS_API_KEY) }, walletPasses: { appleConfigured: Boolean(process.env.APPLE_PASS_CERTIFICATE), googleConfigured: Boolean(process.env.GOOGLE_WALLET_CREDENTIALS) } }));
router.get('/admin/integrations/environment', requirePlatformRole, (_req, res) => res.json({ variables: environmentVariableAudit(), note: 'Names and presence only. Secret values are never returned.' }));

export default router;
