-- PostgreSQL requires new enum values to commit before they are used as defaults.
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SUPER_ADMIN';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'ADMIN';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SUPPORT';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'TENANT_STAFF';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'MARKETPLACE_USER';
