'use client';

import { useEffect, useState } from 'react';
import { adminFetch } from '@/lib/adminFetch';

async function request(path, options) { const response = await adminFetch(path, options); const data = await response.json(); if (!response.ok) throw new Error(data?.error || 'Request failed'); return data; }
const ASSETS = ['BTC','ETH','SOL','ADA','USDC','USDT'];

export default function CryptoAdminPage() {
  const [settings, setSettings] = useState({ enabled: false, provider: 'MOCK', acceptedAssets: ['BTC','ETH','SOL','ADA','USDC','USDT'], requiredConfirmations: 2, invoiceExpiryMinutes: 30 }); const [invoices, setInvoices] = useState([]); const [message, setMessage] = useState('');
  async function load() { try { const tenantSettings = await request('/crypto/settings'); setSettings(tenantSettings || settings); try { setInvoices(await request('/crypto/admin/invoices')); } catch {} } catch (error) { setMessage(error.message); } }
  useEffect(() => { load(); }, []);
  async function save() { try { setSettings(await request('/crypto/settings', { method: 'PUT', body: JSON.stringify(settings) })); setMessage('Crypto settings saved. Use MOCK only for testing; it does not collect real funds.'); } catch (error) { setMessage(error.message); } }
  return <main className="container grid" style={{ gap: 24 }}><section className="card"><h1>Crypto Checkout</h1><p className="muted">Configure accepted assets, confirmations, and invoice expiry. Orders are not paid until confirmation thresholds are reached.</p>{message ? <p className="success">{message}</p> : null}</section><section className="card grid grid-2"><label className="checkbox-row"><input type="checkbox" checked={settings.enabled} onChange={(event) => setSettings({ ...settings, enabled: event.target.checked })} /> Enable crypto checkout</label><div className="field"><label>Provider</label><select value={settings.provider} onChange={(event) => setSettings({ ...settings, provider: event.target.value })}><option value="MOCK">MOCK (test only)</option></select></div><div className="field"><label>Required confirmations</label><input type="number" min="1" value={settings.requiredConfirmations} onChange={(event) => setSettings({ ...settings, requiredConfirmations: Number(event.target.value) })} /></div><div className="field"><label>Invoice expiry (minutes)</label><input type="number" min="5" value={settings.invoiceExpiryMinutes} onChange={(event) => setSettings({ ...settings, invoiceExpiryMinutes: Number(event.target.value) })} /></div><div className="action-row" style={{ gridColumn: '1 / -1', flexWrap: 'wrap' }}>{ASSETS.map((asset) => <label className="checkbox-row" key={asset}><input type="checkbox" checked={(settings.acceptedAssets || []).includes(asset)} onChange={(event) => setSettings({ ...settings, acceptedAssets: event.target.checked ? [...settings.acceptedAssets, asset] : settings.acceptedAssets.filter((item) => item !== asset) })} /> {asset}</label>)}</div><button className="btn" onClick={save}>Save crypto settings</button></section><section className="card"><h2>Crypto invoices</h2><div style={{ overflowX: 'auto' }}><table className="table"><thead><tr><th>Tenant/customer</th><th>Asset</th><th>Fiat</th><th>Crypto</th><th>Status</th><th>Confirmations</th></tr></thead><tbody>{invoices.map((invoice) => <tr key={invoice.id}><td>{invoice.tenant?.name}<div className="muted small">{invoice.order?.customerEmail}</div></td><td>{invoice.asset} · {invoice.chain}</td><td>${(invoice.fiatAmountCents / 100).toFixed(2)}</td><td>{Number(invoice.cryptoAmount).toFixed(8)}</td><td>{invoice.status}</td><td>{invoice.confirmations}/{invoice.requiredConfirmations}</td></tr>)}</tbody></table></div></section></main>;
}
