'use client';

import { useCallback, useEffect, useState } from 'react';
import { apiFetch } from '../../../lib/api';
import { ErrorState, LoadingState, PageHeader, StatusBadge } from '../../../components/ui/LoadlyxUI';

const SERVICE_TYPES = ['FACTORING','QUICK_PAY','FUEL_CARD','FUEL_OPTIMIZATION','AUTHORITY','INSURANCE','COMPLIANCE','PERMITS','ELD','TAX','LEGAL','MAINTENANCE','TIRE','ROADSIDE','TRAINING','ACCOUNTING'];
const blank = { serviceType:'FACTORING', name:'', providerKey:'', status:'PARTNER_REQUIRED', regions:'CA, US', revenueShareBps:'', externalApiConfigured:false, enabled:false };

export default function AdminServices() {
  const [rows,setRows]=useState(null); const [form,setForm]=useState(blank); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [saving,setSaving]=useState(false);
  const load=useCallback(()=>apiFetch('/services/admin/partners').then(setRows).catch(e=>setError(e.message)),[]);
  useEffect(()=>{ load(); },[load]);
  async function save(event){event.preventDefault();setSaving(true);setError('');setNotice('');try{await apiFetch('/services/admin/partners',{method:'POST',body:JSON.stringify({...form,regions:form.regions.split(',').map(value=>value.trim()).filter(Boolean),revenueShareBps:form.revenueShareBps===''?undefined:Number(form.revenueShareBps)})});setNotice('Service partner configuration saved and audited.');setForm(blank);await load();}catch(e){setError(e.message)}finally{setSaving(false)}}
  function edit(row){setForm({serviceType:row.serviceType,name:row.name,providerKey:row.providerKey,status:row.status,regions:(row.regionsJson||[]).join(', '),revenueShareBps:row.revenueShareBps??'',externalApiConfigured:Boolean(row.externalApiConfigured),enabled:Boolean(row.enabled)});window.scrollTo({top:0,behavior:'smooth'})}
  return <main className="container grid" style={{gap:24}}>
    <PageHeader eyebrow="Freight service control plane" title="Partners, availability, regions, eligibility and revenue share." description="Super Admin controls which independent services are visible. Disabled or unconfigured products never appear as live."/>
    <form className="card grid" style={{gap:16}} onSubmit={save}><h2>Configure an independent service partner</h2><p className="muted">Loadlyx is the integration and referral platform. Regulated products remain unavailable until a real provider and required API configuration are approved.</p><div className="form-grid"><label>Service type<select value={form.serviceType} onChange={e=>setForm({...form,serviceType:e.target.value})}>{SERVICE_TYPES.map(value=><option key={value}>{value}</option>)}</select></label><label>Partner name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Provider key<input required value={form.providerKey} onChange={e=>setForm({...form,providerKey:e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,'-')})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{['AVAILABLE','PARTNER_REQUIRED','COMING_SOON','CONFIGURATION_REQUIRED','DISABLED'].map(value=><option key={value}>{value}</option>)}</select></label><label>Regions<input value={form.regions} onChange={e=>setForm({...form,regions:e.target.value})}/></label><label>Revenue share (basis points)<input type="number" min="0" max="10000" value={form.revenueShareBps} onChange={e=>setForm({...form,revenueShareBps:e.target.value})}/></label></div><div className="action-row"><label><input type="checkbox" checked={form.externalApiConfigured} onChange={e=>setForm({...form,externalApiConfigured:e.target.checked})}/> External API configured</label><label><input type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/> Enabled</label><button className="btn" disabled={saving}>{saving?'Saving…':'Save configuration'}</button></div>{notice?<p className="success">{notice}</p>:null}</form>
    {error?<ErrorState message={error}/>:rows===null?<LoadingState label="Loading service partners"/>:<section className="card"><table className="table"><thead><tr><th>Service</th><th>Partner</th><th>Status</th><th>API</th><th>Revenue share</th><th>Action</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td>{row.serviceType}</td><td>{row.name}</td><td><StatusBadge>{row.status}</StatusBadge></td><td>{row.externalApiConfigured?'Configured':'Required'}</td><td>{row.revenueShareBps==null?'Not configured':`${row.revenueShareBps/100}%`}</td><td><button className="btn ghost" type="button" onClick={()=>edit(row)}>Edit</button></td></tr>)}</tbody></table>{!rows.length?<p className="muted">No partner is configured. Regulated services remain Partner Required.</p>:null}</section>}
  </main>
}
