'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { adminFetch } from '../../../lib/adminFetch';
import { EmptyState, ErrorState, LoadingState, PageHeader, StatusBadge } from '../../../components/ui/LoadlyxUI';
const money = (value, currency = 'CAD') => new Intl.NumberFormat('en-CA', { style: 'currency', currency: currency.toUpperCase() }).format((value || 0) / 100);

export default function MarketplaceOffersPage() {
  const [loads, setLoads] = useState(null); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  async function load() { const response = await adminFetch('/marketplace/loads/mine'); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Unable to load offers'); setLoads(data); }
  useEffect(() => { load().catch((err) => setError(err.message)); }, []);
  async function accept(loadRow, offer) { if (!window.confirm(`Accept ${money(offer.amountCents, offer.currency)} from ${offer.bidder.fullName || offer.bidder.role}? This creates the payable agreement.`)) return; const key = crypto.randomUUID(); try { const response = await adminFetch(`/marketplace/loads/${loadRow.id}/award/${offer.id}`, { method: 'POST', headers: { 'Idempotency-Key': key }, body: JSON.stringify({ idempotencyKey: key }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Unable to accept offer'); setMessage('Offer accepted. Its terms and fee rule were snapshotted into a payable agreement.'); await load(); } catch (err) { setError(err.message); } }
  async function counter(loadRow, offer) { const raw = window.prompt('Counter amount in dollars', (offer.amountCents / 100).toFixed(2)); if (!raw) return; const conditions = window.prompt('Counter conditions', offer.conditions || '') ?? offer.conditions; try { const response = await adminFetch(`/marketplace/loads/${loadRow.id}/offers/${offer.id}/counter`, { method: 'POST', body: JSON.stringify({ amountCents: Math.round(Number(raw) * 100), currency: offer.currency || 'cad', message: `Counter from Loadlyx negotiation workspace`, conditions }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Unable to counter offer'); setMessage('Counteroffer recorded in the immutable offer history.'); await load(); } catch (err) { setError(err.message); } }
  return <main className="container grid" style={{ gap: 24 }}><PageHeader eyebrow="Negotiated marketplace" title="Offers and agreement history" description="Review comparable offer terms, counter without overwriting history, and accept exactly one offer into a payable transaction." actions={<Link className="btn" href="/loadboard">Open load board</Link>}/>{error ? <ErrorState message={error}/> : null}{message ? <p className="success">{message}</p> : null}{loads === null ? <LoadingState label="Loading offers"/> : loads.length ? loads.map((loadRow) => <section className="card" key={loadRow.id}><div className="panel-header"><div><StatusBadge>{loadRow.status}</StatusBadge><h2>{loadRow.title}</h2><p className="muted">{loadRow.originCity} → {loadRow.destinationCity}</p></div><strong>{loadRow.bids?.length || 0} offers</strong></div><div className="stack-sm">{(loadRow.bids || []).map((offer) => <article className="summary-line" key={offer.id}><span><strong>{offer.bidder.fullName || offer.bidder.role} · {money(offer.amountCents, offer.currency)}</strong><small>{offer.status} · version {offer.version} · {offer.transitDays ? `${offer.transitDays} transit days` : 'Transit time open'}</small><small>{offer.conditions || offer.message || 'No additional conditions'}</small></span><div className="action-row">{['SUBMITTED','VIEWED','COUNTERED'].includes(offer.status) ? <><button className="btn ghost" onClick={() => counter(loadRow, offer)}>Counter</button><button className="btn" onClick={() => accept(loadRow, offer)}>Accept offer</button></> : null}</div></article>)}</div></section>) : <EmptyState title="No offers connected to this account" description="Post a load or complete provider onboarding and submit an offer."/>}</main>;
}
