import Link from 'next/link';
import { notFound } from 'next/navigation';

const API_URL=process.env.NEXT_PUBLIC_API_URL||'http://localhost:4000/api';
async function request(path,slug){const response=await fetch(`${API_URL}${path}`,{cache:'no-store',headers:{'Content-Type':'application/json','x-tenant-slug':slug}});if(response.status===404)return null;if(!response.ok)throw new Error(`Store request failed (${response.status})`);return response.json();}
function money(product){const cents=product.productType==='RENTAL'?Number(product.weeklyRateCents||product.priceCents):Number(product.salePriceCents||product.priceCents);return `$${(cents/100).toFixed(2)}${product.productType==='RENTAL'?'/week':''}`;}
function ProductCard({product,slug}){const image=product.primaryImage?.url||product.images?.[0]?.url;return <article className="tenant-product-card"><Link href={`/tenant/${slug}/catalog/${product.slug}`} className="tenant-product-media">{image?<img src={image} alt={product.primaryImage?.altText||product.name}/>:<span>{product.category?.name||'Store item'}</span>}{product.salePriceCents?<b>Sale</b>:null}</Link><div className="tenant-product-content"><small>{product.category?.name||'Featured'}</small><Link href={`/tenant/${slug}/catalog/${product.slug}`}>{product.name}</Link><p>{product.description||'Store-ready products and services from this local business.'}</p><div><strong>{money(product)}</strong><Link href={`/tenant/${slug}/catalog/${product.slug}`}>View product →</Link></div></div></article>;}

export default async function TenantHomePage({params}){
 let tenant,products=[];try{tenant=await request(`/tenant/by-slug/${params.slug}`,params.slug);const data=await request('/products',params.slug);products=Array.isArray(data)?data:(data?.products||[]);}catch{return <main className="tenant-store"><div className="tenant-store-shell"><section className="tenant-empty"><h1>Store temporarily unavailable</h1><p>Please try again in a moment.</p></section></div></main>;}
 if(!tenant)return notFound();
 const branding=tenant.branding||{};const tokens=tenant.theme?.settings?.tokens||{};const name=tenant.name||params.slug;const primary=branding.primaryColor||tokens.primaryColor||'#175c4c';const accent=branding.accentColor||tokens.accentColor||'#e9b949';const heroImage=branding.pageImageUrl||'';const categories=[...new Map(products.filter(row=>row.category).map(row=>[row.category.id,row.category])).values()].slice(0,6);const featured=products.slice(0,8);const tote=branding.businessType==='TOTE_RENTAL';
 return <main className="tenant-store" style={{'--store-primary':primary,'--store-accent':accent}} data-store-theme={tenant.theme?.key||'loadlyx-modern'}>
  {branding.promoBannerEnabled&&branding.promoBanner?<div className="tenant-announcement">{branding.promoBanner}</div>:null}
  <header className="tenant-store-header"><div className="tenant-store-header-main"><Link href={`/tenant/${params.slug}`} className="tenant-store-brand">{branding.logoUrl?<img src={branding.logoUrl} alt=""/>:<span>{name.slice(0,1)}</span>}<strong>{name}</strong></Link><nav><Link href={`/tenant/${params.slug}`}>Home</Link><Link href={`/tenant/${params.slug}/catalog`}>Shop</Link><Link href={`/tenant/${params.slug}/quote`}>Get a quote</Link>{(branding.tenantPages||[]).filter(page=>page.showInNav!==false).slice(0,2).map(page=><Link key={page.slug} href={`/tenant/${params.slug}/pages/${page.slug}`}>{page.navLabel||page.title}</Link>)}</nav><div className="tenant-store-actions"><Link href={`/tenant/${params.slug}/catalog`}>Search</Link><Link className="tenant-cart-link" href={`/tenant/${params.slug}/catalog`}>Cart</Link></div></div></header>
  <div className="tenant-store-shell">
   <section className={`tenant-store-hero ${heroImage?'has-image':''}`}>{heroImage?<img src={heroImage} alt={branding.bannerAlt||`${name} storefront`}/>:null}<div className="tenant-store-hero-copy"><span>{tote?'Saskatoon tote rentals':'Shop local. Move better.'}</span><h1>{branding.heroHeading||branding.heroTitle||`Everything you need for your next move.`}</h1><p>{branding.heroDescription||branding.heroSubtitle||'Moving supplies, protection, and trusted services—organized in one simple storefront.'}</p><div><Link className="tenant-store-primary" href={`/tenant/${params.slug}/catalog`}>{branding.ctaText||'Shop the collection'}</Link><Link className="tenant-store-secondary" href={`/tenant/${params.slug}/quote`}>Request a quote</Link></div></div></section>
   <section className="tenant-service-strip"><div><b>Secure checkout</b><span>Protected payment options</span></div><div><b>Local support</b><span>{branding.contactEmail||'Help when you need it'}</span></div><div><b>Tenant fulfilled</b><span>Orders managed by {name}</span></div><div><b>Transparent pricing</b><span>Review totals before payment</span></div></section>
   {categories.length?<section className="tenant-store-section"><div className="tenant-section-heading"><div><span>Browse the store</span><h2>Shop by category</h2></div><Link href={`/tenant/${params.slug}/catalog`}>View all products</Link></div><div className="tenant-category-grid">{categories.map((category,index)=><Link href={`/tenant/${params.slug}/catalog?category=${encodeURIComponent(category.name)}`} key={category.id}><i>{category.icon||String(index+1).padStart(2,'0')}</i><strong>{category.name}</strong><span>{category.description||'Explore products'} →</span></Link>)}</div></section>:null}
   {featured.length?<section className="tenant-store-section"><div className="tenant-section-heading"><div><span>Curated for your move</span><h2>Featured products</h2></div><Link href={`/tenant/${params.slug}/catalog`}>Shop all</Link></div><div className="tenant-products-grid">{featured.map(product=><ProductCard key={product.id} product={product} slug={params.slug}/>)}</div></section>:null}
   {tote?<section className="tenant-editorial"><div><span>Simple tote rentals</span><h2>Move without the cardboard mountain.</h2><p>{branding.rentalTerms||'Choose your package, receive clean totes before move day, and schedule pickup after your move. Two-week minimum.'}</p><Link href={`/tenant/${params.slug}/catalog`}>See rental packages</Link></div><ol>{['Choose a package','Select your move date','Receive clean totes','Schedule easy pickup'].map((item,index)=><li key={item}><b>{index+1}</b><span>{item}</span></li>)}</ol></section>:<section className="tenant-editorial"><div><span>More than a supply store</span><h2>{branding.trustHeadline||'From packing supplies to a booked move.'}</h2><p>{branding.trustCopy||'Shop essentials, request a quote, and coordinate moving services from the same local storefront.'}</p><Link href={`/tenant/${params.slug}/quote`}>Plan your move</Link></div><ol>{['Browse trusted products','Build your cart','Choose payment','Track fulfilment'].map((item,index)=><li key={item}><b>{index+1}</b><span>{item}</span></li>)}</ol></section>}
   {(branding.faq||[]).length?<section className="tenant-store-section tenant-faq"><div className="tenant-section-heading"><div><span>Need to know</span><h2>Frequently asked questions</h2></div></div>{branding.faq.map(item=><details key={item.question}><summary>{item.question}</summary><p>{item.answer}</p></details>)}</section>:null}
   <section className="tenant-final-cta"><span>Ready when you are</span><h2>{branding.footerHeading||`Start your order with ${name}.`}</h2><p>{branding.footerDescription||'Browse the catalog or request a personalized moving quote.'}</p><div><Link href={`/tenant/${params.slug}/catalog`}>Shop now</Link><Link href={`/tenant/${params.slug}/quote`}>Get a quote</Link></div></section>
  </div>
  <footer className="tenant-store-footer"><div><Link href={`/tenant/${params.slug}`} className="tenant-store-brand"><span>{name.slice(0,1)}</span><strong>{name}</strong></Link><p>{branding.footerDescription||'Moving supplies and services, delivered through a secure Loadlyx storefront.'}</p></div><nav><b>Shop</b><Link href={`/tenant/${params.slug}/catalog`}>All products</Link><Link href={`/tenant/${params.slug}/quote`}>Request a quote</Link></nav><nav><b>Customer care</b>{branding.contactEmail?<a href={`mailto:${branding.contactEmail}`}>{branding.contactEmail}</a>:null}{branding.contactPhone?<a href={`tel:${branding.contactPhone}`}>{branding.contactPhone}</a>:null}<span>{branding.serviceArea||branding.contactAddress||'Local service area'}</span></nav><nav><b>Follow</b>{branding.facebookUrl?<a href={branding.facebookUrl}>Facebook</a>:null}{branding.instagramUrl?<a href={branding.instagramUrl}>Instagram</a>:null}{branding.linkedinUrl?<a href={branding.linkedinUrl}>LinkedIn</a>:null}<small>Powered by Loadlyx</small></nav></footer>
 </main>;
}
