export const homepageDefaults = [
  { key: 'hero', enabled: true, displayOrder: 10, eyebrow: 'AI logistics operating system', headline: 'Turn more demand into booked, profitable work.', supportingText: 'Loadlyx connects lead capture, quotes, follow-up, dispatch, marketplace opportunities, storefront commerce, payments, analytics, and governed AI automation.', ctaLabel: 'Start free', ctaUrl: '/signup', secondaryCtaLabel: 'See how it works', secondaryCtaUrl: '#how-it-works', visualVariant: 'default', items: [] },
  { key: 'problems', enabled: true, displayOrder: 20, eyebrow: 'The operational gap', headline: 'Too much revenue is lost between the lead and the completed job.', supportingText: 'When the customer journey and operating workflow live in separate systems, teams repeat work and opportunities disappear.', ctaLabel: '', ctaUrl: '', visualVariant: 'default', items: [] },
  { key: 'solution', enabled: true, displayOrder: 30, eyebrow: 'One connected system', headline: 'Turn operational work into coordinated workflows.', supportingText: 'Loadlyx helps each role move from insight to action while keeping important decisions visible and reviewable.', ctaLabel: '', ctaUrl: '', visualVariant: 'default', items: [] },
  { key: 'social-proof', enabled: true, displayOrder: 40, eyebrow: 'Designed around real roles', headline: 'One platform. A clear path for every participant.', supportingText: 'No fabricated logos or testimonials—just role-specific workflows represented in the Loadlyx architecture.', ctaLabel: '', ctaUrl: '', visualVariant: 'default', items: [] },
  { key: 'how-it-works', enabled: true, displayOrder: 50, eyebrow: 'How it works', headline: 'Get operational in three connected steps.', supportingText: 'Start with the workflow creating the most friction, then connect the rest of the revenue path.', ctaLabel: '', ctaUrl: '', visualVariant: 'default', items: [] },
  { key: 'why-loadlyx', enabled: true, displayOrder: 60, eyebrow: 'Why Loadlyx', headline: 'Built around the full logistics revenue loop—not one isolated task.', supportingText: 'Most tools stop at CRM, dispatch, marketplace, or commerce. Loadlyx connects them while preserving role and tenant boundaries.', ctaLabel: 'Explore solutions', ctaUrl: '/solutions', visualVariant: 'default', items: [] },
  { key: 'comparison', enabled: true, displayOrder: 70, eyebrow: 'The connected advantage', headline: 'Reasons operators choose a unified system.', supportingText: '', ctaLabel: '', ctaUrl: '', visualVariant: 'default', items: [] },
  { key: 'features', enabled: true, displayOrder: 80, eyebrow: 'Platform capabilities', headline: 'Everything required to see, run, and grow the operation.', supportingText: 'A shared design language keeps public commerce, tenant operations, and platform administration distinct but connected.', ctaLabel: '', ctaUrl: '', visualVariant: 'default', items: [] },
  { key: 'faq', enabled: true, displayOrder: 90, eyebrow: 'Frequently asked questions', headline: 'Clear answers before you commit.', supportingText: '', ctaLabel: '', ctaUrl: '', visualVariant: 'default', items: [] },
  { key: 'final-cta', enabled: true, displayOrder: 100, eyebrow: 'Build the connected operation', headline: 'See what your business can run from one place.', supportingText: 'Create an account to explore the current Loadlyx workflows, or review the platform structure first.', ctaLabel: 'Start free', ctaUrl: '/signup', secondaryCtaLabel: 'View pricing', secondaryCtaUrl: '/pricing', visualVariant: 'default', items: [] }
];
